# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# main.py
import sys
from PyQt5.QtWidgets import QApplication
from utility import DatabaseUtils,Messages
from controllers import MainController



if __name__ == "__main__":
    try:
        app = QApplication(sys.argv)
        DatabaseUtils.check_database()
        main_window = MainController()
        main_window.show()
        sys.exit(app.exec_())
    except Exception as e:
        Messages.show_error_msg(str(e))
