from .PatientsController import *
from .DoctorsController import *
from .ServicesController import *
from .ReportsController import *
from .AppointmentsController import *
from .ExpenseController import *
from .MainController import *
from .MedicalRecordsController import *
from .PatientFileController import *
