# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .resources_rc import *


class Ui_patientFile(object):
    def setupUi(self, patientFile_form):
        patientFile_form.setObjectName("patientFile_form")
        patientFile_form.resize(1190, 709)
        patientFile_form.setMinimumSize(QtCore.QSize(1190, 709))
        patientFile_form.setMaximumSize(QtCore.QSize(1190, 709))
        self.tabWidget = QtWidgets.QTabWidget(patientFile_form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1191, 711))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(9999, 99999))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 5px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.patientInfo_tab = QtWidgets.QWidget()
        self.patientInfo_tab.setObjectName("patientInfo_tab")
        self.addAppointment_btn = QtWidgets.QPushButton(self.patientInfo_tab)
        self.addAppointment_btn.setGeometry(QtCore.QRect(310, 600, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addAppointment_btn.setFont(font)
        self.addAppointment_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addAppointment_btn.setStyleSheet("QPushButton {\n"
"    background-color: #17a2b8; /* Bootstrap info blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #138496; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #117a8b; /* Even darker blue on press */\n"
"}\n"
"")
        self.addAppointment_btn.setObjectName("addAppointment_btn")
        self.editPatient_btn = QtWidgets.QPushButton(self.patientInfo_tab)
        self.editPatient_btn.setGeometry(QtCore.QRect(720, 600, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.editPatient_btn.setFont(font)
        self.editPatient_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.editPatient_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ffc107; /* Bootstrap warning yellow */\n"
"    color: #212529; /* Dark text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0a800; /* Darker yellow on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c69500; /* Even darker yellow on press */\n"
"}\n"
"")
        self.editPatient_btn.setObjectName("editPatient_btn")
        self.deletePatient_btn = QtWidgets.QPushButton(self.patientInfo_tab)
        self.deletePatient_btn.setGeometry(QtCore.QRect(920, 600, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.deletePatient_btn.setFont(font)
        self.deletePatient_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.deletePatient_btn.setStyleSheet("QPushButton{\n"
"    background-color: #dc3545; /* Bootstrap danger red */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c82333; /* Darker red on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #bd2130; /* Even darker red on press */\n"
"}\n"
"")
        self.deletePatient_btn.setObjectName("deletePatient_btn")
        self.addNewMedicalRecord_btn = QtWidgets.QPushButton(self.patientInfo_tab)
        self.addNewMedicalRecord_btn.setGeometry(QtCore.QRect(500, 600, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addNewMedicalRecord_btn.setFont(font)
        self.addNewMedicalRecord_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addNewMedicalRecord_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addNewMedicalRecord_btn.setObjectName("addNewMedicalRecord_btn")
        self.patientFullName_lbl_11 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_11.setGeometry(QtCore.QRect(1060, 110, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_11.setFont(font)
        self.patientFullName_lbl_11.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_11.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_11.setObjectName("patientFullName_lbl_11")
        self.patientFullName_lbl_12 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_12.setGeometry(QtCore.QRect(1060, 210, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_12.setFont(font)
        self.patientFullName_lbl_12.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_12.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_12.setObjectName("patientFullName_lbl_12")
        self.patientFullName_lbl_13 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_13.setGeometry(QtCore.QRect(1060, 160, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_13.setFont(font)
        self.patientFullName_lbl_13.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_13.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_13.setObjectName("patientFullName_lbl_13")
        self.patientFullName_lbl_14 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_14.setGeometry(QtCore.QRect(1060, 260, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_14.setFont(font)
        self.patientFullName_lbl_14.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_14.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_14.setObjectName("patientFullName_lbl_14")
        self.patientFullName_lbl_15 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_15.setGeometry(QtCore.QRect(1060, 480, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_15.setFont(font)
        self.patientFullName_lbl_15.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_15.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_15.setObjectName("patientFullName_lbl_15")
        self.patientFullName_lbl_16 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_16.setGeometry(QtCore.QRect(1060, 410, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_16.setFont(font)
        self.patientFullName_lbl_16.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_16.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_16.setObjectName("patientFullName_lbl_16")
        self.firstName_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.firstName_lbl.setGeometry(QtCore.QRect(600, 60, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.firstName_lbl.setFont(font)
        self.firstName_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.firstName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.firstName_lbl.setObjectName("firstName_lbl")
        self.lastName_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.lastName_lbl.setGeometry(QtCore.QRect(600, 110, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lastName_lbl.setFont(font)
        self.lastName_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.lastName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lastName_lbl.setObjectName("lastName_lbl")
        self.age_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.age_lbl.setGeometry(QtCore.QRect(600, 210, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.age_lbl.setFont(font)
        self.age_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.age_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.age_lbl.setObjectName("age_lbl")
        self.identityCode_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.identityCode_lbl.setGeometry(QtCore.QRect(600, 160, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.identityCode_lbl.setFont(font)
        self.identityCode_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.identityCode_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.identityCode_lbl.setObjectName("identityCode_lbl")
        self.phoneNumber_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.phoneNumber_lbl.setGeometry(QtCore.QRect(600, 260, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.phoneNumber_lbl.setFont(font)
        self.phoneNumber_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.phoneNumber_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.phoneNumber_lbl.setObjectName("phoneNumber_lbl")
        self.printPatientFIle_btn = QtWidgets.QPushButton(self.patientInfo_tab)
        self.printPatientFIle_btn.setGeometry(QtCore.QRect(160, 600, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.printPatientFIle_btn.setFont(font)
        self.printPatientFIle_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.printPatientFIle_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(204, 204, 204);\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(181, 181, 181);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(143, 143, 143);\n"
"}\n"
"  \n"
"\n"
"")
        self.printPatientFIle_btn.setObjectName("printPatientFIle_btn")
        self.patientFullName_lbl_9 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_9.setGeometry(QtCore.QRect(1060, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_9.setFont(font)
        self.patientFullName_lbl_9.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_9.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_9.setObjectName("patientFullName_lbl_9")
        self.label_18 = QtWidgets.QLabel(self.patientInfo_tab)
        self.label_18.setGeometry(QtCore.QRect(480, 490, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.specialCondition_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.specialCondition_lbl.setGeometry(QtCore.QRect(10, 490, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.specialCondition_lbl.setFont(font)
        self.specialCondition_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.specialCondition_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.specialCondition_lbl.setObjectName("specialCondition_lbl")
        self.label_19 = QtWidgets.QLabel(self.patientInfo_tab)
        self.label_19.setGeometry(QtCore.QRect(300, 530, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pregnant_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.pregnant_lbl.setGeometry(QtCore.QRect(10, 530, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pregnant_lbl.setFont(font)
        self.pregnant_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.pregnant_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pregnant_lbl.setObjectName("pregnant_lbl")
        self.patientFullName_lbl_17 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_17.setGeometry(QtCore.QRect(1060, 310, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_17.setFont(font)
        self.patientFullName_lbl_17.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_17.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_17.setObjectName("patientFullName_lbl_17")
        self.job_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.job_lbl.setGeometry(QtCore.QRect(600, 310, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.job_lbl.setFont(font)
        self.job_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.job_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.job_lbl.setObjectName("job_lbl")
        self.maritalStatus_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.maritalStatus_lbl.setGeometry(QtCore.QRect(600, 360, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.maritalStatus_lbl.setFont(font)
        self.maritalStatus_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.maritalStatus_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.maritalStatus_lbl.setObjectName("maritalStatus_lbl")
        self.patientFullName_lbl_18 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_18.setGeometry(QtCore.QRect(1060, 360, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_18.setFont(font)
        self.patientFullName_lbl_18.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_18.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_18.setObjectName("patientFullName_lbl_18")
        self.groupBox_11 = QtWidgets.QGroupBox(self.patientInfo_tab)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 150, 581, 161))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gastrointestinal_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.gastrointestinal_chkbox.setEnabled(False)
        self.gastrointestinal_chkbox.setGeometry(QtCore.QRect(440, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.gastrointestinal_chkbox.setFont(font)
        self.gastrointestinal_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gastrointestinal_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.gastrointestinal_chkbox.setObjectName("gastrointestinal_chkbox")
        self.respiratory_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.respiratory_chkbox.setEnabled(False)
        self.respiratory_chkbox.setGeometry(QtCore.QRect(150, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.respiratory_chkbox.setFont(font)
        self.respiratory_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.respiratory_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.respiratory_chkbox.setObjectName("respiratory_chkbox")
        self.blood_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.blood_chkbox.setEnabled(False)
        self.blood_chkbox.setGeometry(QtCore.QRect(10, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.blood_chkbox.setFont(font)
        self.blood_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.blood_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.blood_chkbox.setObjectName("blood_chkbox")
        self.herpes_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.herpes_chkbox.setEnabled(False)
        self.herpes_chkbox.setGeometry(QtCore.QRect(440, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.herpes_chkbox.setFont(font)
        self.herpes_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.herpes_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.herpes_chkbox.setObjectName("herpes_chkbox")
        self.label_15 = QtWidgets.QLabel(self.groupBox_11)
        self.label_15.setGeometry(QtCore.QRect(500, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.kidney_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.kidney_chkbox.setEnabled(False)
        self.kidney_chkbox.setGeometry(QtCore.QRect(150, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.kidney_chkbox.setFont(font)
        self.kidney_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kidney_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.kidney_chkbox.setObjectName("kidney_chkbox")
        self.hormone_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.hormone_chkbox.setEnabled(False)
        self.hormone_chkbox.setGeometry(QtCore.QRect(10, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hormone_chkbox.setFont(font)
        self.hormone_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hormone_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.hormone_chkbox.setObjectName("hormone_chkbox")
        self.thyroidDisease_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.thyroidDisease_chkbox.setEnabled(False)
        self.thyroidDisease_chkbox.setGeometry(QtCore.QRect(360, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.thyroidDisease_chkbox.setFont(font)
        self.thyroidDisease_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thyroidDisease_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.thyroidDisease_chkbox.setObjectName("thyroidDisease_chkbox")
        self.cancer_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.cancer_chkbox.setEnabled(False)
        self.cancer_chkbox.setGeometry(QtCore.QRect(290, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cancer_chkbox.setFont(font)
        self.cancer_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancer_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.cancer_chkbox.setObjectName("cancer_chkbox")
        self.hepatitis_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.hepatitis_chkbox.setEnabled(False)
        self.hepatitis_chkbox.setGeometry(QtCore.QRect(360, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hepatitis_chkbox.setFont(font)
        self.hepatitis_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hepatitis_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.hepatitis_chkbox.setObjectName("hepatitis_chkbox")
        self.MS_chkbox = QtWidgets.QCheckBox(self.groupBox_11)
        self.MS_chkbox.setEnabled(False)
        self.MS_chkbox.setGeometry(QtCore.QRect(290, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.MS_chkbox.setFont(font)
        self.MS_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MS_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.MS_chkbox.setObjectName("MS_chkbox")
        self.diseaseOtherItems_lbl = QtWidgets.QLabel(self.groupBox_11)
        self.diseaseOtherItems_lbl.setGeometry(QtCore.QRect(20, 110, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.diseaseOtherItems_lbl.setFont(font)
        self.diseaseOtherItems_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.diseaseOtherItems_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.diseaseOtherItems_lbl.setObjectName("diseaseOtherItems_lbl")
        self.groupBox_12 = QtWidgets.QGroupBox(self.patientInfo_tab)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 320, 581, 161))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_12.setObjectName("groupBox_12")
        self.contraceptive_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.contraceptive_chkbox.setEnabled(False)
        self.contraceptive_chkbox.setGeometry(QtCore.QRect(440, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.contraceptive_chkbox.setFont(font)
        self.contraceptive_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.contraceptive_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.contraceptive_chkbox.setObjectName("contraceptive_chkbox")
        self.sedative_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.sedative_chkbox.setEnabled(False)
        self.sedative_chkbox.setGeometry(QtCore.QRect(150, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sedative_chkbox.setFont(font)
        self.sedative_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sedative_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.sedative_chkbox.setObjectName("sedative_chkbox")
        self.heart_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.heart_chkbox.setEnabled(False)
        self.heart_chkbox.setGeometry(QtCore.QRect(20, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.heart_chkbox.setFont(font)
        self.heart_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heart_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.heart_chkbox.setObjectName("heart_chkbox")
        self.anticoagulants_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.anticoagulants_chkbox.setEnabled(False)
        self.anticoagulants_chkbox.setGeometry(QtCore.QRect(440, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.anticoagulants_chkbox.setFont(font)
        self.anticoagulants_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.anticoagulants_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.anticoagulants_chkbox.setObjectName("anticoagulants_chkbox")
        self.label_17 = QtWidgets.QLabel(self.groupBox_12)
        self.label_17.setGeometry(QtCore.QRect(500, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.antibioticsMedicine_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.antibioticsMedicine_chkbox.setEnabled(False)
        self.antibioticsMedicine_chkbox.setGeometry(QtCore.QRect(150, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.antibioticsMedicine_chkbox.setFont(font)
        self.antibioticsMedicine_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.antibioticsMedicine_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.antibioticsMedicine_chkbox.setObjectName("antibioticsMedicine_chkbox")
        self.Minoxidil_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.Minoxidil_chkbox.setEnabled(False)
        self.Minoxidil_chkbox.setGeometry(QtCore.QRect(20, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Minoxidil_chkbox.setFont(font)
        self.Minoxidil_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Minoxidil_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.Minoxidil_chkbox.setObjectName("Minoxidil_chkbox")
        self.aspirin_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.aspirin_chkbox.setEnabled(False)
        self.aspirin_chkbox.setGeometry(QtCore.QRect(360, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.aspirin_chkbox.setFont(font)
        self.aspirin_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aspirin_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.aspirin_chkbox.setObjectName("aspirin_chkbox")
        self.thyroidMedicine_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.thyroidMedicine_chkbox.setEnabled(False)
        self.thyroidMedicine_chkbox.setGeometry(QtCore.QRect(270, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.thyroidMedicine_chkbox.setFont(font)
        self.thyroidMedicine_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thyroidMedicine_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.thyroidMedicine_chkbox.setObjectName("thyroidMedicine_chkbox")
        self.insulin_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.insulin_chkbox.setEnabled(False)
        self.insulin_chkbox.setGeometry(QtCore.QRect(360, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.insulin_chkbox.setFont(font)
        self.insulin_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.insulin_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.insulin_chkbox.setObjectName("insulin_chkbox")
        self.roaccutane_chkbox = QtWidgets.QCheckBox(self.groupBox_12)
        self.roaccutane_chkbox.setEnabled(False)
        self.roaccutane_chkbox.setGeometry(QtCore.QRect(270, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.roaccutane_chkbox.setFont(font)
        self.roaccutane_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.roaccutane_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.roaccutane_chkbox.setObjectName("roaccutane_chkbox")
        self.medicationOtherItems_lbl = QtWidgets.QLabel(self.groupBox_12)
        self.medicationOtherItems_lbl.setGeometry(QtCore.QRect(20, 110, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.medicationOtherItems_lbl.setFont(font)
        self.medicationOtherItems_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.medicationOtherItems_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.medicationOtherItems_lbl.setObjectName("medicationOtherItems_lbl")
        self.groupBox_10 = QtWidgets.QGroupBox(self.patientInfo_tab)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 581, 131))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_10.setObjectName("groupBox_10")
        self.antibioticsAllergy_chkbox = QtWidgets.QCheckBox(self.groupBox_10)
        self.antibioticsAllergy_chkbox.setEnabled(False)
        self.antibioticsAllergy_chkbox.setGeometry(QtCore.QRect(440, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.antibioticsAllergy_chkbox.setFont(font)
        self.antibioticsAllergy_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.antibioticsAllergy_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.antibioticsAllergy_chkbox.setCheckable(True)
        self.antibioticsAllergy_chkbox.setChecked(False)
        self.antibioticsAllergy_chkbox.setObjectName("antibioticsAllergy_chkbox")
        self.localAnesthetic_chkbox = QtWidgets.QCheckBox(self.groupBox_10)
        self.localAnesthetic_chkbox.setEnabled(False)
        self.localAnesthetic_chkbox.setGeometry(QtCore.QRect(240, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.localAnesthetic_chkbox.setFont(font)
        self.localAnesthetic_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.localAnesthetic_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.localAnesthetic_chkbox.setObjectName("localAnesthetic_chkbox")
        self.painkiller_chkbox = QtWidgets.QCheckBox(self.groupBox_10)
        self.painkiller_chkbox.setEnabled(False)
        self.painkiller_chkbox.setGeometry(QtCore.QRect(130, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.painkiller_chkbox.setFont(font)
        self.painkiller_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.painkiller_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.painkiller_chkbox.setObjectName("painkiller_chkbox")
        self.specialFood_chkbox = QtWidgets.QCheckBox(self.groupBox_10)
        self.specialFood_chkbox.setEnabled(False)
        self.specialFood_chkbox.setGeometry(QtCore.QRect(20, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.specialFood_chkbox.setFont(font)
        self.specialFood_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.specialFood_chkbox.setStyleSheet(" QCheckBox{\n"
"        background-color: none;\n"
"        color: black;\n"
"    }")
        self.specialFood_chkbox.setObjectName("specialFood_chkbox")
        self.label_14 = QtWidgets.QLabel(self.groupBox_10)
        self.label_14.setGeometry(QtCore.QRect(510, 80, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.allergyOtherItems_lbl = QtWidgets.QLabel(self.groupBox_10)
        self.allergyOtherItems_lbl.setGeometry(QtCore.QRect(20, 80, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.allergyOtherItems_lbl.setFont(font)
        self.allergyOtherItems_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.allergyOtherItems_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.allergyOtherItems_lbl.setObjectName("allergyOtherItems_lbl")
        self.extraInfo_lbl = QtWidgets.QTextEdit(self.patientInfo_tab)
        self.extraInfo_lbl.setGeometry(QtCore.QRect(600, 480, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        self.extraInfo_lbl.setFont(font)
        self.extraInfo_lbl.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.extraInfo_lbl.setStyleSheet("/* Basic LineEdit styling */\n"
"QTextEdit {\n"
"    background-color: rgb(233, 236, 239);\n"
"    border: 1px solid;\n"
"    border-color: rgb(206, 206, 206); \n"
"    border-radius: 5px; /* Rounded corners */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"\n"
"/* Focus effect */\n"
"QTextEdit:focus {\n"
"\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QTextEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.extraInfo_lbl.setReadOnly(True)
        self.extraInfo_lbl.setObjectName("extraInfo_lbl")
        self.address_lbl = QtWidgets.QTextEdit(self.patientInfo_tab)
        self.address_lbl.setGeometry(QtCore.QRect(600, 410, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        self.address_lbl.setFont(font)
        self.address_lbl.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.address_lbl.setStyleSheet("/* Basic LineEdit styling */\n"
"QTextEdit {\n"
"    background-color: rgb(233, 236, 239);\n"
"    border: 1px solid;\n"
"    border-color: rgb(206, 206, 206); \n"
"    border-radius: 5px; /* Rounded corners */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"\n"
"/* Focus effect */\n"
"QTextEdit:focus {\n"
"\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QTextEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.address_lbl.setReadOnly(True)
        self.address_lbl.setObjectName("address_lbl")
        self.fileNumber_lbl = QtWidgets.QLabel(self.patientInfo_tab)
        self.fileNumber_lbl.setGeometry(QtCore.QRect(600, 10, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.fileNumber_lbl.setFont(font)
        self.fileNumber_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.fileNumber_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fileNumber_lbl.setObjectName("fileNumber_lbl")
        self.patientFullName_lbl_10 = QtWidgets.QLabel(self.patientInfo_tab)
        self.patientFullName_lbl_10.setGeometry(QtCore.QRect(1060, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.patientFullName_lbl_10.setFont(font)
        self.patientFullName_lbl_10.setStyleSheet("border: 1px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(232, 232, 232);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 98, 167);\n"
"\n"
"")
        self.patientFullName_lbl_10.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl_10.setObjectName("patientFullName_lbl_10")
        self.openPatientFolder_btn = QtWidgets.QPushButton(self.patientInfo_tab)
        self.openPatientFolder_btn.setGeometry(QtCore.QRect(90, 600, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.openPatientFolder_btn.setFont(font)
        self.openPatientFolder_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.openPatientFolder_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(204, 204, 204);\n"
"    \n"
"    background-color: rgb(230, 230, 230);\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(199, 199, 199);\n"
"\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(143, 143, 143);\n"
"}\n"
"  \n"
"\n"
"")
        self.openPatientFolder_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openPatientFolder_btn.setIcon(icon)
        self.openPatientFolder_btn.setIconSize(QtCore.QSize(35, 35))
        self.openPatientFolder_btn.setObjectName("openPatientFolder_btn")
        self.tabWidget.addTab(self.patientInfo_tab, "")
        self.appointments_tab = QtWidgets.QWidget()
        self.appointments_tab.setObjectName("appointments_tab")
        self.userAppointments_lst = QtWidgets.QListWidget(self.appointments_tab)
        self.userAppointments_lst.setGeometry(QtCore.QRect(10, 10, 1171, 651))
        self.userAppointments_lst.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.userAppointments_lst.setFont(font)
        self.userAppointments_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.userAppointments_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 5px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.userAppointments_lst.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.userAppointments_lst.setObjectName("userAppointments_lst")
        self.tabWidget.addTab(self.appointments_tab, "")
        self.medicalRecords_tab = QtWidgets.QWidget()
        self.medicalRecords_tab.setObjectName("medicalRecords_tab")
        self.userMedicalRecords_lst = QtWidgets.QListWidget(self.medicalRecords_tab)
        self.userMedicalRecords_lst.setGeometry(QtCore.QRect(10, 10, 1171, 651))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.userMedicalRecords_lst.setFont(font)
        self.userMedicalRecords_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.userMedicalRecords_lst.setStyleSheet("")
        self.userMedicalRecords_lst.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.userMedicalRecords_lst.setObjectName("userMedicalRecords_lst")
        self.tabWidget.addTab(self.medicalRecords_tab, "")
        self.approvalLatter_tab = QtWidgets.QWidget()
        self.approvalLatter_tab.setObjectName("approvalLatter_tab")
        self.groupBox_14 = QtWidgets.QGroupBox(self.approvalLatter_tab)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 1161, 141))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_14)
        self.label_16.setGeometry(QtCore.QRect(0, 30, 1151, 101))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(44, 91, 168);")
        self.label_16.setObjectName("label_16")
        self.groupBox_15 = QtWidgets.QGroupBox(self.approvalLatter_tab)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 160, 421, 251))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_15.setStyleSheet("")
        self.groupBox_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.signatureImage_lbl = QtWidgets.QLabel(self.groupBox_15)
        self.signatureImage_lbl.setGeometry(QtCore.QRect(10, 30, 401, 201))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        self.signatureImage_lbl.setFont(font)
        self.signatureImage_lbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.signatureImage_lbl.setText("")
        self.signatureImage_lbl.setPixmap(QtGui.QPixmap("../../../../../Downloads/blank-profile-picture-973460_1920.png"))
        self.signatureImage_lbl.setScaledContents(True)
        self.signatureImage_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.signatureImage_lbl.setWordWrap(False)
        self.signatureImage_lbl.setObjectName("signatureImage_lbl")
        self.tabWidget.addTab(self.approvalLatter_tab, "")

        self.retranslateUi(patientFile_form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(patientFile_form)

    def retranslateUi(self, patientFile_form):
        _translate = QtCore.QCoreApplication.translate
        patientFile_form.setWindowTitle(_translate("patientFile_form", "پرونده بیمار"))
        self.addAppointment_btn.setText(_translate("patientFile_form", "افزودن نوبت"))
        self.editPatient_btn.setText(_translate("patientFile_form", "ویرایش اطلاعات بیمار"))
        self.deletePatient_btn.setText(_translate("patientFile_form", "حذف پرونده بیمار"))
        self.addNewMedicalRecord_btn.setText(_translate("patientFile_form", "افزودن خدمات جدید به پرونده"))
        self.patientFullName_lbl_11.setText(_translate("patientFile_form", "نام خانوادگی"))
        self.patientFullName_lbl_12.setText(_translate("patientFile_form", "سن"))
        self.patientFullName_lbl_13.setText(_translate("patientFile_form", "کد ملی"))
        self.patientFullName_lbl_14.setText(_translate("patientFile_form", "شماره تلفن"))
        self.patientFullName_lbl_15.setText(_translate("patientFile_form", "اطلاعات اضافه"))
        self.patientFullName_lbl_16.setText(_translate("patientFile_form", "آدرس"))
        self.firstName_lbl.setText(_translate("patientFile_form", "-"))
        self.lastName_lbl.setText(_translate("patientFile_form", "-"))
        self.age_lbl.setText(_translate("patientFile_form", "-"))
        self.identityCode_lbl.setText(_translate("patientFile_form", "-"))
        self.phoneNumber_lbl.setText(_translate("patientFile_form", "-"))
        self.printPatientFIle_btn.setText(_translate("patientFile_form", "چاپ پرونده"))
        self.patientFullName_lbl_9.setText(_translate("patientFile_form", "نام بیمار"))
        self.label_18.setText(_translate("patientFile_form", "وضعیت خاص بیمار:"))
        self.specialCondition_lbl.setText(_translate("patientFile_form", "-"))
        self.label_19.setText(_translate("patientFile_form", "بیمار در دوران شیردهی یا بارداری به سر می‌برد؟ (بانوان)"))
        self.pregnant_lbl.setText(_translate("patientFile_form", "-"))
        self.patientFullName_lbl_17.setText(_translate("patientFile_form", "شغل"))
        self.job_lbl.setText(_translate("patientFile_form", "-"))
        self.maritalStatus_lbl.setText(_translate("patientFile_form", "-"))
        self.patientFullName_lbl_18.setText(_translate("patientFile_form", "وضعیت تاهل"))
        self.groupBox_11.setTitle(_translate("patientFile_form", "بیماری‌ها"))
        self.gastrointestinal_chkbox.setText(_translate("patientFile_form", "بیماری‌های گوارشی"))
        self.respiratory_chkbox.setText(_translate("patientFile_form", "بیماری‌های تنفسی"))
        self.blood_chkbox.setText(_translate("patientFile_form", "بیماری‌های خونی"))
        self.herpes_chkbox.setText(_translate("patientFile_form", "ابتلا به تبخال"))
        self.label_15.setText(_translate("patientFile_form", "سایر موارد:"))
        self.kidney_chkbox.setText(_translate("patientFile_form", "بیماری‌های کلیوی"))
        self.hormone_chkbox.setText(_translate("patientFile_form", "اختلالات هورمونی"))
        self.thyroidDisease_chkbox.setText(_translate("patientFile_form", "تیروئید"))
        self.cancer_chkbox.setText(_translate("patientFile_form", "سرطان"))
        self.hepatitis_chkbox.setText(_translate("patientFile_form", "هپاتیت"))
        self.MS_chkbox.setText(_translate("patientFile_form", "ام اس"))
        self.diseaseOtherItems_lbl.setText(_translate("patientFile_form", "-"))
        self.groupBox_12.setTitle(_translate("patientFile_form", "مصرف دارو در دو سال گذشته"))
        self.contraceptive_chkbox.setText(_translate("patientFile_form", "داروی ضد بارداری"))
        self.sedative_chkbox.setText(_translate("patientFile_form", "آرام‌بخش‌ها"))
        self.heart_chkbox.setText(_translate("patientFile_form", "داروی قلبی"))
        self.anticoagulants_chkbox.setText(_translate("patientFile_form", "ضد انعقادها"))
        self.label_17.setText(_translate("patientFile_form", "سایر موارد:"))
        self.antibioticsMedicine_chkbox.setText(_translate("patientFile_form", "آنتی‌بیوتیک‌ها"))
        self.Minoxidil_chkbox.setText(_translate("patientFile_form", "ماینوکسیدیل"))
        self.aspirin_chkbox.setText(_translate("patientFile_form", "آسپرین"))
        self.thyroidMedicine_chkbox.setText(_translate("patientFile_form", "تیروئید"))
        self.insulin_chkbox.setText(_translate("patientFile_form", "انسولین"))
        self.roaccutane_chkbox.setText(_translate("patientFile_form", "راکوتان"))
        self.medicationOtherItems_lbl.setText(_translate("patientFile_form", "-"))
        self.groupBox_10.setTitle(_translate("patientFile_form", "حساسیت‌ها"))
        self.antibioticsAllergy_chkbox.setText(_translate("patientFile_form", "انواع آنتی‌بیوتیک‌ها"))
        self.localAnesthetic_chkbox.setText(_translate("patientFile_form", "داروهای بی‌حسی موضعی"))
        self.painkiller_chkbox.setText(_translate("patientFile_form", "مسکن‌ها"))
        self.specialFood_chkbox.setText(_translate("patientFile_form", "غذای خاص"))
        self.label_14.setText(_translate("patientFile_form", "سایر موارد:"))
        self.allergyOtherItems_lbl.setText(_translate("patientFile_form", "-"))
        self.extraInfo_lbl.setHtml(_translate("patientFile_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Vazirmatn\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Vazirmatn,sans-serif\'; font-size:16px;\">-</span></p></body></html>"))
        self.address_lbl.setHtml(_translate("patientFile_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Vazirmatn\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Vazirmatn,sans-serif\'; font-size:16px;\">-</span></p></body></html>"))
        self.fileNumber_lbl.setText(_translate("patientFile_form", "-"))
        self.patientFullName_lbl_10.setText(_translate("patientFile_form", "شماره پرونده"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.patientInfo_tab), _translate("patientFile_form", "اطلاعات بیمار"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appointments_tab), _translate("patientFile_form", "نوبت‌ها "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.medicalRecords_tab), _translate("patientFile_form", "خدمات"))
        self.groupBox_14.setTitle(_translate("patientFile_form", "متن رضایت‌نامه"))
        self.label_16.setText(_translate("patientFile_form", "  بدینوسیله به پزشک معالج خود اين اجازه را می دهم که اعمال لازم را برای اينجانب انجام دهد. اينجانب تاييد می نمايم كه مفاد اين اجازه نامه را در وضع \n"
" عادى مطالعه و امضاء نموده‌ا‌م و از عوارض احتمالى اعمال زيبايى كه براى من توضيح داده‌اند مطلع مى باشم."))
        self.groupBox_15.setTitle(_translate("patientFile_form", "امضاء بیمار"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.approvalLatter_tab), _translate("patientFile_form", "رضایت‌نامه"))
