from .add_edit_delete_doctors import *
from .add_edit_medical_records import *
from .add_edit_patient import *
from .add_edit_delete_service import *
from .main_window import *
from .patient_file import *
from .add_edit_appointment import *
from .appointment_info import *
from .medical_record_info import *