# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_service.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addService_form(object):
    def setupUi(self, addService_form):
        addService_form.setObjectName("addService_form")
        addService_form.resize(427, 219)
        addService_form.setMinimumSize(QtCore.QSize(427, 219))
        addService_form.setMaximumSize(QtCore.QSize(427, 219))
        self.label_5 = QtWidgets.QLabel(addService_form)
        self.label_5.setGeometry(QtCore.QRect(340, 90, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.serviceName_txtbox = QtWidgets.QLineEdit(addService_form)
        self.serviceName_txtbox.setGeometry(QtCore.QRect(20, 80, 321, 31))
        self.serviceName_txtbox.setMinimumSize(QtCore.QSize(321, 31))
        self.serviceName_txtbox.setMaximumSize(QtCore.QSize(321, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.serviceName_txtbox.setFont(font)
        self.serviceName_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.serviceName_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.serviceName_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.serviceName_txtbox.setObjectName("serviceName_txtbox")
        self.label_4 = QtWidgets.QLabel(addService_form)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(addService_form)
        self.label_6.setGeometry(QtCore.QRect(340, 130, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.servicePrice_spnbox = QtWidgets.QSpinBox(addService_form)
        self.servicePrice_spnbox.setGeometry(QtCore.QRect(20, 120, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(13)
        self.servicePrice_spnbox.setFont(font)
        self.servicePrice_spnbox.setStyleSheet("")
        self.servicePrice_spnbox.setAlignment(QtCore.Qt.AlignCenter)
        self.servicePrice_spnbox.setMinimum(100)
        self.servicePrice_spnbox.setMaximum(1000000000)
        self.servicePrice_spnbox.setObjectName("servicePrice_spnbox")
        self.save_btn = QtWidgets.QPushButton(addService_form)
        self.save_btn.setGeometry(QtCore.QRect(164, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("QPushButton {\n"
"    background-color: #28a745; /* Bootstrap success green */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #218838; /* Darker green on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34; /* Even darker green on press */\n"
"}\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.cancel_btn = QtWidgets.QPushButton(addService_form)
        self.cancel_btn.setGeometry(QtCore.QRect(260, 170, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"    background-color: #cccccc; /* Light grey */\n"
"    color: #212529; /* Dark text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b3b3b3; /* Darker grey on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #999999; /* Even darker grey on press */\n"
"}\n"
"")
        self.cancel_btn.setCheckable(False)
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(addService_form)
        QtCore.QMetaObject.connectSlotsByName(addService_form)

    def retranslateUi(self, addService_form):
        _translate = QtCore.QCoreApplication.translate
        addService_form.setWindowTitle(_translate("addService_form", "افزودن سرویس"))
        self.label_5.setText(_translate("addService_form", "نام سرویس:"))
        self.label_4.setText(_translate("addService_form", "اضافه کردن سرویس"))
        self.label_6.setText(_translate("addService_form", "قیمت:"))
        self.save_btn.setText(_translate("addService_form", "ثبت"))
        self.cancel_btn.setText(_translate("addService_form", "لغو"))

