# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appointment_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_appointmentInfo_form(object):
    def setupUi(self, appointmentInfo_form):
        appointmentInfo_form.setObjectName("appointmentInfo_form")
        appointmentInfo_form.resize(678, 516)
        appointmentInfo_form.setMinimumSize(QtCore.QSize(678, 516))
        appointmentInfo_form.setMaximumSize(QtCore.QSize(678, 516))
        self.sendReminderSMS_btn = QtWidgets.QPushButton(appointmentInfo_form)
        self.sendReminderSMS_btn.setGeometry(QtCore.QRect(30, 450, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sendReminderSMS_btn.setFont(font)
        self.sendReminderSMS_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.sendReminderSMS_btn.setObjectName("sendReminderSMS_btn")
        self.addAppointmentToMedicalRecords_btn = QtWidgets.QPushButton(appointmentInfo_form)
        self.addAppointmentToMedicalRecords_btn.setGeometry(QtCore.QRect(220, 450, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addAppointmentToMedicalRecords_btn.setFont(font)
        self.addAppointmentToMedicalRecords_btn.setStyleSheet("QPushButton {\n"
"    background-color: #17a2b8; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addAppointmentToMedicalRecords_btn.setObjectName("addAppointmentToMedicalRecords_btn")
        self.editAppointment_btn = QtWidgets.QPushButton(appointmentInfo_form)
        self.editAppointment_btn.setGeometry(QtCore.QRect(450, 450, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.editAppointment_btn.setFont(font)
        self.editAppointment_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.editAppointment_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ffc107; /* Bootstrap warning yellow */\n"
"    color: #212529; /* Dark text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0a800; /* Darker yellow on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c69500; /* Even darker yellow on press */\n"
"}\n"
"")
        self.editAppointment_btn.setObjectName("editAppointment_btn")
        self.deleteAppointment_btn = QtWidgets.QPushButton(appointmentInfo_form)
        self.deleteAppointment_btn.setGeometry(QtCore.QRect(560, 450, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.deleteAppointment_btn.setFont(font)
        self.deleteAppointment_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.deleteAppointment_btn.setStyleSheet("QPushButton{\n"
"    background-color: #dc3545; /* Bootstrap danger red */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c82333; /* Darker red on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #bd2130; /* Even darker red on press */\n"
"}\n"
"")
        self.deleteAppointment_btn.setObjectName("deleteAppointment_btn")
        self.label_35 = QtWidgets.QLabel(appointmentInfo_form)
        self.label_35.setGeometry(QtCore.QRect(550, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.patientFullName_lbl = QtWidgets.QLabel(appointmentInfo_form)
        self.patientFullName_lbl.setGeometry(QtCore.QRect(30, 40, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.patientFullName_lbl.setFont(font)
        self.patientFullName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl.setObjectName("patientFullName_lbl")
        self.line = QtWidgets.QFrame(appointmentInfo_form)
        self.line.setGeometry(QtCore.QRect(30, 70, 621, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.datetime_lbl = QtWidgets.QLabel(appointmentInfo_form)
        self.datetime_lbl.setGeometry(QtCore.QRect(26, 140, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.datetime_lbl.setFont(font)
        self.datetime_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.datetime_lbl.setObjectName("datetime_lbl")
        self.line_7 = QtWidgets.QFrame(appointmentInfo_form)
        self.line_7.setGeometry(QtCore.QRect(530, 30, 20, 351))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_2 = QtWidgets.QFrame(appointmentInfo_form)
        self.line_2.setGeometry(QtCore.QRect(30, 170, 621, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_39 = QtWidgets.QLabel(appointmentInfo_form)
        self.label_39.setGeometry(QtCore.QRect(550, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.line_3 = QtWidgets.QFrame(appointmentInfo_form)
        self.line_3.setGeometry(QtCore.QRect(30, 220, 621, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_40 = QtWidgets.QLabel(appointmentInfo_form)
        self.label_40.setGeometry(QtCore.QRect(550, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.line_4 = QtWidgets.QFrame(appointmentInfo_form)
        self.line_4.setGeometry(QtCore.QRect(30, 270, 621, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_44 = QtWidgets.QLabel(appointmentInfo_form)
        self.label_44.setGeometry(QtCore.QRect(550, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(appointmentInfo_form)
        self.label_45.setGeometry(QtCore.QRect(550, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.line_5 = QtWidgets.QFrame(appointmentInfo_form)
        self.line_5.setGeometry(QtCore.QRect(30, 320, 621, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_46 = QtWidgets.QLabel(appointmentInfo_form)
        self.label_46.setGeometry(QtCore.QRect(550, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.doctorName_lbl = QtWidgets.QLabel(appointmentInfo_form)
        self.doctorName_lbl.setGeometry(QtCore.QRect(30, 190, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.doctorName_lbl.setFont(font)
        self.doctorName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.doctorName_lbl.setObjectName("doctorName_lbl")
        self.serviceName_lbl = QtWidgets.QLabel(appointmentInfo_form)
        self.serviceName_lbl.setGeometry(QtCore.QRect(30, 240, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.serviceName_lbl.setFont(font)
        self.serviceName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.serviceName_lbl.setObjectName("serviceName_lbl")
        self.status_lbl = QtWidgets.QLabel(appointmentInfo_form)
        self.status_lbl.setGeometry(QtCore.QRect(30, 290, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.status_lbl.setFont(font)
        self.status_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.status_lbl.setObjectName("status_lbl")
        self.description_lbl = QtWidgets.QLabel(appointmentInfo_form)
        self.description_lbl.setGeometry(QtCore.QRect(30, 340, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        self.description_lbl.setFont(font)
        self.description_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.description_lbl.setObjectName("description_lbl")
        self.line_6 = QtWidgets.QFrame(appointmentInfo_form)
        self.line_6.setGeometry(QtCore.QRect(30, 120, 621, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_47 = QtWidgets.QLabel(appointmentInfo_form)
        self.label_47.setGeometry(QtCore.QRect(550, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.phoneNumber_lbl = QtWidgets.QLabel(appointmentInfo_form)
        self.phoneNumber_lbl.setGeometry(QtCore.QRect(20, 90, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.phoneNumber_lbl.setFont(font)
        self.phoneNumber_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.phoneNumber_lbl.setObjectName("phoneNumber_lbl")
        self.line_8 = QtWidgets.QFrame(appointmentInfo_form)
        self.line_8.setGeometry(QtCore.QRect(30, 370, 621, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.smsCount_lbl = QtWidgets.QLabel(appointmentInfo_form)
        self.smsCount_lbl.setGeometry(QtCore.QRect(30, 400, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.smsCount_lbl.setFont(font)
        self.smsCount_lbl.setStyleSheet("border: 1px solid;\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.smsCount_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.smsCount_lbl.setObjectName("smsCount_lbl")

        self.retranslateUi(appointmentInfo_form)
        QtCore.QMetaObject.connectSlotsByName(appointmentInfo_form)

    def retranslateUi(self, appointmentInfo_form):
        _translate = QtCore.QCoreApplication.translate
        appointmentInfo_form.setWindowTitle(_translate("appointmentInfo_form", "اطلاعات نوبت"))
        self.sendReminderSMS_btn.setText(_translate("appointmentInfo_form", "ارسال پیامک یادآوری به بیمار"))
        self.addAppointmentToMedicalRecords_btn.setText(_translate("appointmentInfo_form", "اضافه کردن نوبت به خدمات پرونده"))
        self.editAppointment_btn.setText(_translate("appointmentInfo_form", "ویرایش نوبت"))
        self.deleteAppointment_btn.setText(_translate("appointmentInfo_form", "حذف "))
        self.label_35.setText(_translate("appointmentInfo_form", "نام بیمار:"))
        self.patientFullName_lbl.setText(_translate("appointmentInfo_form", "امیررضا خلیلی"))
        self.datetime_lbl.setText(_translate("appointmentInfo_form", "سه‌شنبه ۱۴۰۳/۰۱/۰۵ ۱۵:۳۰"))
        self.label_39.setText(_translate("appointmentInfo_form", "دکتر:"))
        self.label_40.setText(_translate("appointmentInfo_form", "سرویس:"))
        self.label_44.setText(_translate("appointmentInfo_form", "وضعیت:"))
        self.label_45.setText(_translate("appointmentInfo_form", "تاریخ و زمان:"))
        self.label_46.setText(_translate("appointmentInfo_form", "توضیحات:"))
        self.doctorName_lbl.setText(_translate("appointmentInfo_form", "دکتر محمدرضا خلیلی"))
        self.serviceName_lbl.setText(_translate("appointmentInfo_form", "بوتاکس صورت"))
        self.status_lbl.setText(_translate("appointmentInfo_form", "فعال"))
        self.description_lbl.setText(_translate("appointmentInfo_form", "جلسه سوم"))
        self.label_47.setText(_translate("appointmentInfo_form", "شماره تلفن:"))
        self.phoneNumber_lbl.setText(_translate("appointmentInfo_form", "۰۹۰۱۲۷۲۳۵۸۹"))
        self.smsCount_lbl.setText(_translate("appointmentInfo_form", "۲ پیامک یادآوری برای بیمار ارسال شده است"))
