# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChartView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1196, 723)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1196, 723))
        MainWindow.setMaximumSize(QtCore.QSize(1196, 723))
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1201, 671))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn SemiBold")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.groupBox = QtWidgets.QGroupBox(self.main_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 89, 1171, 71))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.patientsIdentityCodeSearch_txtbox = QtWidgets.QLineEdit(self.groupBox)
        self.patientsIdentityCodeSearch_txtbox.setGeometry(QtCore.QRect(200, 30, 201, 31))
        self.patientsIdentityCodeSearch_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.patientsIdentityCodeSearch_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.patientsIdentityCodeSearch_txtbox.setObjectName("patientsIdentityCodeSearch_txtbox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(400, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.patientsLastNameSearch_btn = QtWidgets.QPushButton(self.groupBox)
        self.patientsLastNameSearch_btn.setGeometry(QtCore.QRect(480, 30, 71, 31))
        self.patientsLastNameSearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.patientsLastNameSearch_btn.setObjectName("patientsLastNameSearch_btn")
        self.patientsLastNameSearch_txtbox = QtWidgets.QLineEdit(self.groupBox)
        self.patientsLastNameSearch_txtbox.setGeometry(QtCore.QRect(560, 30, 221, 31))
        self.patientsLastNameSearch_txtbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.patientsLastNameSearch_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.patientsLastNameSearch_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.patientsLastNameSearch_txtbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.patientsLastNameSearch_txtbox.setObjectName("patientsLastNameSearch_txtbox")
        self.patientsIdentityCodeSearch_btn = QtWidgets.QPushButton(self.groupBox)
        self.patientsIdentityCodeSearch_btn.setGeometry(QtCore.QRect(120, 30, 71, 31))
        self.patientsIdentityCodeSearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.patientsIdentityCodeSearch_btn.setObjectName("patientsIdentityCodeSearch_btn")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(760, 30, 101, 31))
        self.label_6.setObjectName("label_6")
        self.refreshPatientsList_btn = QtWidgets.QPushButton(self.groupBox)
        self.refreshPatientsList_btn.setGeometry(QtCore.QRect(940, 30, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.refreshPatientsList_btn.setFont(font)
        self.refreshPatientsList_btn.setStyleSheet("QPushButton {\n"
"    background-color: #17a2b8; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.refreshPatientsList_btn.setObjectName("refreshPatientsList_btn")
        self.label_3 = QtWidgets.QLabel(self.main_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 951, 71))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.patients_lst = QtWidgets.QListWidget(self.main_tab)
        self.patients_lst.setGeometry(QtCore.QRect(10, 170, 1171, 441))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(13)
        self.patients_lst.setFont(font)
        self.patients_lst.setMouseTracking(False)
        self.patients_lst.setAutoFillBackground(False)
        self.patients_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 5px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.patients_lst.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patients_lst.setFrameShadow(QtWidgets.QFrame.Raised)
        self.patients_lst.setLineWidth(1)
        self.patients_lst.setMidLineWidth(0)
        self.patients_lst.setDragDropOverwriteMode(False)
        self.patients_lst.setAlternatingRowColors(False)
        self.patients_lst.setViewMode(QtWidgets.QListView.ListMode)
        self.patients_lst.setUniformItemSizes(False)
        self.patients_lst.setWordWrap(False)
        self.patients_lst.setObjectName("patients_lst")
        self.addPatient_btn = QtWidgets.QPushButton(self.main_tab)
        self.addPatient_btn.setGeometry(QtCore.QRect(970, 10, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addPatient_btn.setFont(font)
        self.addPatient_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addPatient_btn.setObjectName("addPatient_btn")
        self.tabWidget.addTab(self.main_tab, "")
        self.notifications_tab = QtWidgets.QWidget()
        self.notifications_tab.setObjectName("notifications_tab")
        self.appointments_lst = QtWidgets.QListWidget(self.notifications_tab)
        self.appointments_lst.setGeometry(QtCore.QRect(10, 100, 1171, 511))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.appointments_lst.setFont(font)
        self.appointments_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.appointments_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.appointments_lst.setObjectName("appointments_lst")
        self.label_9 = QtWidgets.QLabel(self.notifications_tab)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 311, 71))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.notifications_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(960, 10, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.appointmentSearchByDay_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.appointmentSearchByDay_btn.setGeometry(QtCore.QRect(10, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.appointmentSearchByDay_btn.setFont(font)
        self.appointmentSearchByDay_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.appointmentSearchByDay_btn.setObjectName("appointmentSearchByDay_btn")
        self.appointmentSearchDaySelect_cmbox = QtWidgets.QComboBox(self.groupBox_7)
        self.appointmentSearchDaySelect_cmbox.setEnabled(True)
        self.appointmentSearchDaySelect_cmbox.setGeometry(QtCore.QRect(90, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.appointmentSearchDaySelect_cmbox.setFont(font)
        self.appointmentSearchDaySelect_cmbox.setAcceptDrops(False)
        self.appointmentSearchDaySelect_cmbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.appointmentSearchDaySelect_cmbox.setStyleSheet("")
        self.appointmentSearchDaySelect_cmbox.setEditable(False)
        self.appointmentSearchDaySelect_cmbox.setMaxVisibleItems(10)
        self.appointmentSearchDaySelect_cmbox.setDuplicatesEnabled(False)
        self.appointmentSearchDaySelect_cmbox.setObjectName("appointmentSearchDaySelect_cmbox")
        self.appointmentSearchDaySelect_cmbox.addItem("")
        self.appointmentSearchDaySelect_cmbox.addItem("")
        self.appointmentSearchDaySelect_cmbox.addItem("")
        self.appointmentSearchDaySelect_cmbox.addItem("")
        self.appointmentSearchDaySelect_cmbox.addItem("")
        self.groupBox_8 = QtWidgets.QGroupBox(self.notifications_tab)
        self.groupBox_8.setGeometry(QtCore.QRect(690, 10, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.day_spnbox = QtWidgets.QSpinBox(self.groupBox_8)
        self.day_spnbox.setGeometry(QtCore.QRect(190, 30, 51, 31))
        self.day_spnbox.setMinimum(1)
        self.day_spnbox.setMaximum(31)
        self.day_spnbox.setObjectName("day_spnbox")
        self.month_spnbox = QtWidgets.QSpinBox(self.groupBox_8)
        self.month_spnbox.setGeometry(QtCore.QRect(140, 30, 51, 31))
        self.month_spnbox.setMinimum(1)
        self.month_spnbox.setMaximum(12)
        self.month_spnbox.setObjectName("month_spnbox")
        self.year_spnbox = QtWidgets.QSpinBox(self.groupBox_8)
        self.year_spnbox.setGeometry(QtCore.QRect(80, 30, 61, 31))
        self.year_spnbox.setMinimum(1400)
        self.year_spnbox.setMaximum(1500)
        self.year_spnbox.setObjectName("year_spnbox")
        self.AppointmentSearchByDate_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.AppointmentSearchByDate_btn.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.AppointmentSearchByDate_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.AppointmentSearchByDate_btn.setObjectName("AppointmentSearchByDate_btn")
        self.groupBox_11 = QtWidgets.QGroupBox(self.notifications_tab)
        self.groupBox_11.setGeometry(QtCore.QRect(330, 10, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.sendToAllSMSByDays_cmbox = QtWidgets.QComboBox(self.groupBox_11)
        self.sendToAllSMSByDays_cmbox.setEnabled(True)
        self.sendToAllSMSByDays_cmbox.setGeometry(QtCore.QRect(110, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.sendToAllSMSByDays_cmbox.setFont(font)
        self.sendToAllSMSByDays_cmbox.setAcceptDrops(False)
        self.sendToAllSMSByDays_cmbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sendToAllSMSByDays_cmbox.setStyleSheet("")
        self.sendToAllSMSByDays_cmbox.setEditable(False)
        self.sendToAllSMSByDays_cmbox.setMaxVisibleItems(10)
        self.sendToAllSMSByDays_cmbox.setDuplicatesEnabled(False)
        self.sendToAllSMSByDays_cmbox.setObjectName("sendToAllSMSByDays_cmbox")
        self.sendToAllSMSByDays_cmbox.addItem("")
        self.sendToAllSMSByDays_cmbox.addItem("")
        self.sendToAllSMSByDays_cmbox.addItem("")
        self.sendToAllSMSByDays_cmbox.addItem("")
        self.sendToAllSMSByDays_cmbox.addItem("")
        self.sendToAllSMSByDays_btn = QtWidgets.QPushButton(self.groupBox_11)
        self.sendToAllSMSByDays_btn.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.sendToAllSMSByDays_btn.setFont(font)
        self.sendToAllSMSByDays_btn.setStyleSheet("QPushButton {\n"
"    background-color: #17a2b8; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.sendToAllSMSByDays_btn.setObjectName("sendToAllSMSByDays_btn")
        self.tabWidget.addTab(self.notifications_tab, "")
        self.services_tab = QtWidgets.QWidget()
        self.services_tab.setObjectName("services_tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.services_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 100, 1171, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.searchServices_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.searchServices_btn.setGeometry(QtCore.QRect(700, 30, 111, 31))
        self.searchServices_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    box-shadow: 0 4px rgba(0, 0, 0, 0.2); /* Shadow */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"    box-shadow: 0 2px rgba(0, 0, 0, 0.2); /* Reduce shadow on press */\n"
"    transform: translateY(2px); /* Move button down on press */\n"
"}\n"
"")
        self.searchServices_btn.setObjectName("searchServices_btn")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(1080, 40, 81, 20))
        self.label_11.setObjectName("label_11")
        self.serviceName_txtbox = QtWidgets.QLineEdit(self.groupBox_4)
        self.serviceName_txtbox.setGeometry(QtCore.QRect(820, 30, 261, 31))
        self.serviceName_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.serviceName_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.serviceName_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.serviceName_txtbox.setText("")
        self.serviceName_txtbox.setObjectName("serviceName_txtbox")
        self.addServices_btn = QtWidgets.QPushButton(self.services_tab)
        self.addServices_btn.setGeometry(QtCore.QRect(970, 20, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addServices_btn.setFont(font)
        self.addServices_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addServices_btn.setObjectName("addServices_btn")
        self.label_8 = QtWidgets.QLabel(self.services_tab)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 951, 71))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.services_lst = QtWidgets.QListWidget(self.services_tab)
        self.services_lst.setGeometry(QtCore.QRect(10, 190, 1171, 421))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.services_lst.setFont(font)
        self.services_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.services_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.services_lst.setObjectName("services_lst")
        self.tabWidget.addTab(self.services_tab, "")
        self.medicalRecords_tab = QtWidgets.QWidget()
        self.medicalRecords_tab.setObjectName("medicalRecords_tab")
        self.addDoctor_btn = QtWidgets.QPushButton(self.medicalRecords_tab)
        self.addDoctor_btn.setGeometry(QtCore.QRect(960, 20, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addDoctor_btn.setFont(font)
        self.addDoctor_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addDoctor_btn.setObjectName("addDoctor_btn")
        self.groupBox_5 = QtWidgets.QGroupBox(self.medicalRecords_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 100, 1171, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.searchDoctor_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.searchDoctor_btn.setGeometry(QtCore.QRect(680, 30, 111, 31))
        self.searchDoctor_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.searchDoctor_btn.setObjectName("searchDoctor_btn")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(1070, 40, 71, 20))
        self.label_12.setObjectName("label_12")
        self.doctorName_txtbox = QtWidgets.QLineEdit(self.groupBox_5)
        self.doctorName_txtbox.setGeometry(QtCore.QRect(800, 30, 261, 31))
        self.doctorName_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.doctorName_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"    transition: border-color 0.3s, box-shadow 0.3s; /* Smooth transition */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"    box-shadow: 0 0 5px rgba(0, 123, 255, 0.5); /* Blue shadow on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.doctorName_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.doctorName_txtbox.setText("")
        self.doctorName_txtbox.setObjectName("doctorName_txtbox")
        self.label_4 = QtWidgets.QLabel(self.medicalRecords_tab)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 941, 71))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.doctors_lst = QtWidgets.QListWidget(self.medicalRecords_tab)
        self.doctors_lst.setGeometry(QtCore.QRect(10, 190, 1171, 421))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.doctors_lst.setFont(font)
        self.doctors_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.doctors_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.doctors_lst.setObjectName("doctors_lst")
        self.tabWidget.addTab(self.medicalRecords_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.addExpense_btn = QtWidgets.QPushButton(self.tab_2)
        self.addExpense_btn.setGeometry(QtCore.QRect(970, 10, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addExpense_btn.setFont(font)
        self.addExpense_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addExpense_btn.setObjectName("addExpense_btn")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 951, 61))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(690, 80, 491, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_17 = QtWidgets.QLabel(self.groupBox_10)
        self.label_17.setGeometry(QtCore.QRect(400, 29, 81, 31))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.expenseName_txtbox = QtWidgets.QLineEdit(self.groupBox_10)
        self.expenseName_txtbox.setGeometry(QtCore.QRect(140, 30, 261, 31))
        self.expenseName_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.expenseName_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.expenseName_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.expenseName_txtbox.setText("")
        self.expenseName_txtbox.setObjectName("expenseName_txtbox")
        self.searchExpenseByName_btn = QtWidgets.QPushButton(self.groupBox_10)
        self.searchExpenseByName_btn.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.searchExpenseByName_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    box-shadow: 0 4px rgba(0, 0, 0, 0.2); /* Shadow */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"    box-shadow: 0 2px rgba(0, 0, 0, 0.2); /* Reduce shadow on press */\n"
"    transform: translateY(2px); /* Move button down on press */\n"
"}\n"
"")
        self.searchExpenseByName_btn.setObjectName("searchExpenseByName_btn")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 80, 671, 81))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_9.setObjectName("groupBox_9")
        self.fromDay_spnbox = QtWidgets.QSpinBox(self.groupBox_9)
        self.fromDay_spnbox.setGeometry(QtCore.QRect(530, 30, 51, 31))
        self.fromDay_spnbox.setMinimum(1)
        self.fromDay_spnbox.setMaximum(31)
        self.fromDay_spnbox.setObjectName("fromDay_spnbox")
        self.fromMonth_spnbox = QtWidgets.QSpinBox(self.groupBox_9)
        self.fromMonth_spnbox.setGeometry(QtCore.QRect(480, 30, 51, 31))
        self.fromMonth_spnbox.setMinimum(1)
        self.fromMonth_spnbox.setMaximum(12)
        self.fromMonth_spnbox.setObjectName("fromMonth_spnbox")
        self.fromYear_spnbox = QtWidgets.QSpinBox(self.groupBox_9)
        self.fromYear_spnbox.setGeometry(QtCore.QRect(410, 30, 71, 31))
        self.fromYear_spnbox.setMinimum(1400)
        self.fromYear_spnbox.setMaximum(1500)
        self.fromYear_spnbox.setObjectName("fromYear_spnbox")
        self.searchExpenseByDate_btn = QtWidgets.QPushButton(self.groupBox_9)
        self.searchExpenseByDate_btn.setGeometry(QtCore.QRect(10, 30, 131, 31))
        self.searchExpenseByDate_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.searchExpenseByDate_btn.setObjectName("searchExpenseByDate_btn")
        self.toYear_spnbox = QtWidgets.QSpinBox(self.groupBox_9)
        self.toYear_spnbox.setGeometry(QtCore.QRect(160, 30, 71, 31))
        self.toYear_spnbox.setMinimum(1400)
        self.toYear_spnbox.setMaximum(1500)
        self.toYear_spnbox.setObjectName("toYear_spnbox")
        self.toDay_spnbox = QtWidgets.QSpinBox(self.groupBox_9)
        self.toDay_spnbox.setGeometry(QtCore.QRect(280, 30, 51, 31))
        self.toDay_spnbox.setMinimum(1)
        self.toDay_spnbox.setMaximum(31)
        self.toDay_spnbox.setObjectName("toDay_spnbox")
        self.toMonth_spnbox = QtWidgets.QSpinBox(self.groupBox_9)
        self.toMonth_spnbox.setGeometry(QtCore.QRect(230, 30, 51, 31))
        self.toMonth_spnbox.setMinimum(1)
        self.toMonth_spnbox.setMaximum(12)
        self.toMonth_spnbox.setObjectName("toMonth_spnbox")
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setGeometry(QtCore.QRect(570, 30, 81, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_9)
        self.label_15.setGeometry(QtCore.QRect(320, 30, 81, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.expense_lst = QtWidgets.QListWidget(self.tab_2)
        self.expense_lst.setGeometry(QtCore.QRect(10, 170, 1171, 441))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.expense_lst.setFont(font)
        self.expense_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.expense_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.expense_lst.setObjectName("expense_lst")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.report_chart = QChartView(self.tab)
        self.report_chart.setGeometry(QtCore.QRect(10, 270, 1171, 351))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(15)
        self.report_chart.setFont(font)
        self.report_chart.setStyleSheet("")
        self.report_chart.setObjectName("report_chart")
        self.report_stackedWidget = QtWidgets.QStackedWidget(self.tab)
        self.report_stackedWidget.setGeometry(QtCore.QRect(10, 10, 1041, 251))
        self.report_stackedWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.report_stackedWidget.setStyleSheet("QStackedWidget {\n"
"    background-color:rgb(248, 248, 248);\n"
"    border-radius: 7px; /* Rounded corners */\n"
"}\n"
"\n"
"")
        self.report_stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.report_stackedWidget.setLineWidth(0)
        self.report_stackedWidget.setMidLineWidth(0)
        self.report_stackedWidget.setObjectName("report_stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.line_7 = QtWidgets.QFrame(self.page)
        self.line_7.setGeometry(QtCore.QRect(490, 10, 20, 231))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(540, 30, 231, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_35 = QtWidgets.QLabel(self.page)
        self.label_35.setGeometry(QtCore.QRect(320, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.line_8 = QtWidgets.QFrame(self.page)
        self.line_8.setGeometry(QtCore.QRect(280, 10, 20, 231))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_37 = QtWidgets.QLabel(self.page)
        self.label_37.setGeometry(QtCore.QRect(40, 10, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.page)
        self.label_38.setGeometry(QtCore.QRect(540, 11, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.line_3 = QtWidgets.QFrame(self.page)
        self.line_3.setGeometry(QtCore.QRect(40, 30, 231, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.generalTime_cmbox = QtWidgets.QComboBox(self.page)
        self.generalTime_cmbox.setEnabled(True)
        self.generalTime_cmbox.setGeometry(QtCore.QRect(800, 170, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.generalTime_cmbox.setFont(font)
        self.generalTime_cmbox.setAcceptDrops(False)
        self.generalTime_cmbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.generalTime_cmbox.setStyleSheet("")
        self.generalTime_cmbox.setEditable(False)
        self.generalTime_cmbox.setMaxVisibleItems(10)
        self.generalTime_cmbox.setDuplicatesEnabled(False)
        self.generalTime_cmbox.setObjectName("generalTime_cmbox")
        self.generalTime_cmbox.addItem("")
        self.generalTime_cmbox.addItem("")
        self.generalTime_cmbox.addItem("")
        self.line_4 = QtWidgets.QFrame(self.page)
        self.line_4.setGeometry(QtCore.QRect(320, 30, 151, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.generalIncome_lbl = QtWidgets.QLabel(self.page)
        self.generalIncome_lbl.setGeometry(QtCore.QRect(540, 50, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.generalIncome_lbl.setFont(font)
        self.generalIncome_lbl.setStyleSheet("border: 1px solid;\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.generalIncome_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.generalIncome_lbl.setObjectName("generalIncome_lbl")
        self.label_39 = QtWidgets.QLabel(self.page)
        self.label_39.setGeometry(QtCore.QRect(540, 90, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setGeometry(QtCore.QRect(540, 109, 231, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.generalExpense_lbl = QtWidgets.QLabel(self.page)
        self.generalExpense_lbl.setGeometry(QtCore.QRect(540, 129, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.generalExpense_lbl.setFont(font)
        self.generalExpense_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.generalExpense_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.generalExpense_lbl.setObjectName("generalExpense_lbl")
        self.profitType_lbl = QtWidgets.QLabel(self.page)
        self.profitType_lbl.setGeometry(QtCore.QRect(540, 171, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.profitType_lbl.setFont(font)
        self.profitType_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.profitType_lbl.setObjectName("profitType_lbl")
        self.line_5 = QtWidgets.QFrame(self.page)
        self.line_5.setGeometry(QtCore.QRect(540, 190, 231, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.generalProfit_lbl = QtWidgets.QLabel(self.page)
        self.generalProfit_lbl.setGeometry(QtCore.QRect(540, 210, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.generalProfit_lbl.setFont(font)
        self.generalProfit_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.generalProfit_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.generalProfit_lbl.setObjectName("generalProfit_lbl")
        self.refreshGeneralReport_btn = QtWidgets.QPushButton(self.page)
        self.refreshGeneralReport_btn.setGeometry(QtCore.QRect(800, 210, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.refreshGeneralReport_btn.setFont(font)
        self.refreshGeneralReport_btn.setStyleSheet("QPushButton {\n"
"    background-color: #17a2b8; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.refreshGeneralReport_btn.setObjectName("refreshGeneralReport_btn")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(800, 10, 221, 141))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.n0ServiceHighSold_lbl = QtWidgets.QLabel(self.page)
        self.n0ServiceHighSold_lbl.setGeometry(QtCore.QRect(300, 50, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.n0ServiceHighSold_lbl.setFont(font)
        self.n0ServiceHighSold_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 10px;\n"
"border-color: rgb(206, 206, 206); ")
        self.n0ServiceHighSold_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n0ServiceHighSold_lbl.setObjectName("n0ServiceHighSold_lbl")
        self.n1ServiceHighSold_lbl = QtWidgets.QLabel(self.page)
        self.n1ServiceHighSold_lbl.setGeometry(QtCore.QRect(300, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.n1ServiceHighSold_lbl.setFont(font)
        self.n1ServiceHighSold_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n1ServiceHighSold_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n1ServiceHighSold_lbl.setObjectName("n1ServiceHighSold_lbl")
        self.n2ServiceHighSold_lbl = QtWidgets.QLabel(self.page)
        self.n2ServiceHighSold_lbl.setGeometry(QtCore.QRect(300, 150, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.n2ServiceHighSold_lbl.setFont(font)
        self.n2ServiceHighSold_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n2ServiceHighSold_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n2ServiceHighSold_lbl.setObjectName("n2ServiceHighSold_lbl")
        self.n3ServiceHighSold_lbl = QtWidgets.QLabel(self.page)
        self.n3ServiceHighSold_lbl.setGeometry(QtCore.QRect(300, 200, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.n3ServiceHighSold_lbl.setFont(font)
        self.n3ServiceHighSold_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n3ServiceHighSold_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n3ServiceHighSold_lbl.setObjectName("n3ServiceHighSold_lbl")
        self.n0HighestExpense_lbl = QtWidgets.QLabel(self.page)
        self.n0HighestExpense_lbl.setGeometry(QtCore.QRect(20, 50, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(10)
        self.n0HighestExpense_lbl.setFont(font)
        self.n0HighestExpense_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n0HighestExpense_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n0HighestExpense_lbl.setObjectName("n0HighestExpense_lbl")
        self.n1HighestExpense_lbl = QtWidgets.QLabel(self.page)
        self.n1HighestExpense_lbl.setGeometry(QtCore.QRect(20, 100, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(10)
        self.n1HighestExpense_lbl.setFont(font)
        self.n1HighestExpense_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n1HighestExpense_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n1HighestExpense_lbl.setObjectName("n1HighestExpense_lbl")
        self.n2HighestExpense_lbl = QtWidgets.QLabel(self.page)
        self.n2HighestExpense_lbl.setGeometry(QtCore.QRect(20, 150, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(10)
        self.n2HighestExpense_lbl.setFont(font)
        self.n2HighestExpense_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n2HighestExpense_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n2HighestExpense_lbl.setObjectName("n2HighestExpense_lbl")
        self.n3HighestExpense_lbl = QtWidgets.QLabel(self.page)
        self.n3HighestExpense_lbl.setGeometry(QtCore.QRect(20, 200, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(10)
        self.n3HighestExpense_lbl.setFont(font)
        self.n3HighestExpense_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n3HighestExpense_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n3HighestExpense_lbl.setObjectName("n3HighestExpense_lbl")
        self.report_stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.refreshServiceReport_btn = QtWidgets.QPushButton(self.page_2)
        self.refreshServiceReport_btn.setGeometry(QtCore.QRect(790, 190, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.refreshServiceReport_btn.setFont(font)
        self.refreshServiceReport_btn.setStyleSheet("QPushButton {\n"
"    background-color: #17a2b8; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.refreshServiceReport_btn.setObjectName("refreshServiceReport_btn")
        self.serviceReportTime_cmbox = QtWidgets.QComboBox(self.page_2)
        self.serviceReportTime_cmbox.setEnabled(True)
        self.serviceReportTime_cmbox.setGeometry(QtCore.QRect(790, 150, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.serviceReportTime_cmbox.setFont(font)
        self.serviceReportTime_cmbox.setAcceptDrops(False)
        self.serviceReportTime_cmbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.serviceReportTime_cmbox.setStyleSheet("")
        self.serviceReportTime_cmbox.setEditable(False)
        self.serviceReportTime_cmbox.setMaxVisibleItems(10)
        self.serviceReportTime_cmbox.setDuplicatesEnabled(False)
        self.serviceReportTime_cmbox.setObjectName("serviceReportTime_cmbox")
        self.serviceReportTime_cmbox.addItem("")
        self.serviceReportTime_cmbox.addItem("")
        self.serviceReportTime_cmbox.addItem("")
        self.reportService_cmbox = QtWidgets.QComboBox(self.page_2)
        self.reportService_cmbox.setEnabled(True)
        self.reportService_cmbox.setGeometry(QtCore.QRect(790, 110, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        self.reportService_cmbox.setFont(font)
        self.reportService_cmbox.setAcceptDrops(False)
        self.reportService_cmbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.reportService_cmbox.setStyleSheet("")
        self.reportService_cmbox.setEditable(False)
        self.reportService_cmbox.setMaxVisibleItems(10)
        self.reportService_cmbox.setDuplicatesEnabled(False)
        self.reportService_cmbox.setObjectName("reportService_cmbox")
        self.reportService_cmbox.addItem("")
        self.n3DayServiceHighSell_lbl = QtWidgets.QLabel(self.page_2)
        self.n3DayServiceHighSell_lbl.setGeometry(QtCore.QRect(10, 190, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(10)
        self.n3DayServiceHighSell_lbl.setFont(font)
        self.n3DayServiceHighSell_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n3DayServiceHighSell_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n3DayServiceHighSell_lbl.setObjectName("n3DayServiceHighSell_lbl")
        self.label_50 = QtWidgets.QLabel(self.page_2)
        self.label_50.setGeometry(QtCore.QRect(30, 0, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.n0DayServiceHighSell_lbl = QtWidgets.QLabel(self.page_2)
        self.n0DayServiceHighSell_lbl.setGeometry(QtCore.QRect(10, 40, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(10)
        self.n0DayServiceHighSell_lbl.setFont(font)
        self.n0DayServiceHighSell_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n0DayServiceHighSell_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n0DayServiceHighSell_lbl.setObjectName("n0DayServiceHighSell_lbl")
        self.n2DayServiceHighSell_lbl = QtWidgets.QLabel(self.page_2)
        self.n2DayServiceHighSell_lbl.setGeometry(QtCore.QRect(10, 140, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(10)
        self.n2DayServiceHighSell_lbl.setFont(font)
        self.n2DayServiceHighSell_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n2DayServiceHighSell_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n2DayServiceHighSell_lbl.setObjectName("n2DayServiceHighSell_lbl")
        self.line_6 = QtWidgets.QFrame(self.page_2)
        self.line_6.setGeometry(QtCore.QRect(30, 20, 221, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.n1DayServiceHighSell_lbl = QtWidgets.QLabel(self.page_2)
        self.n1DayServiceHighSell_lbl.setGeometry(QtCore.QRect(10, 90, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(10)
        self.n1DayServiceHighSell_lbl.setFont(font)
        self.n1DayServiceHighSell_lbl.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(232, 232, 232);\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206);  border-radius: 10px;")
        self.n1DayServiceHighSell_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.n1DayServiceHighSell_lbl.setObjectName("n1DayServiceHighSell_lbl")
        self.label_51 = QtWidgets.QLabel(self.page_2)
        self.label_51.setGeometry(QtCore.QRect(320, 140, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.line_9 = QtWidgets.QFrame(self.page_2)
        self.line_9.setGeometry(QtCore.QRect(320, 159, 231, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.serviceIncome_lbl = QtWidgets.QLabel(self.page_2)
        self.serviceIncome_lbl.setGeometry(QtCore.QRect(320, 179, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.serviceIncome_lbl.setFont(font)
        self.serviceIncome_lbl.setStyleSheet("border: 1px solid;\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.serviceIncome_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.serviceIncome_lbl.setObjectName("serviceIncome_lbl")
        self.line_10 = QtWidgets.QFrame(self.page_2)
        self.line_10.setGeometry(QtCore.QRect(290, 0, 20, 231))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(310, 20, 721, 71))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_61 = QtWidgets.QLabel(self.page_2)
        self.label_61.setGeometry(QtCore.QRect(580, 140, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.serviceCount_lbl = QtWidgets.QLabel(self.page_2)
        self.serviceCount_lbl.setGeometry(QtCore.QRect(580, 179, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Medium")
        font.setPointSize(11)
        self.serviceCount_lbl.setFont(font)
        self.serviceCount_lbl.setStyleSheet("border: 1px solid;\n"
"background-color: rgb(233, 236, 239);\n"
"border-radius: 5px;\n"
"border-color: rgb(206, 206, 206); ")
        self.serviceCount_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.serviceCount_lbl.setObjectName("serviceCount_lbl")
        self.line_11 = QtWidgets.QFrame(self.page_2)
        self.line_11.setGeometry(QtCore.QRect(580, 159, 191, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.report_stackedWidget.addWidget(self.page_2)
        self.generalReport_btn = QtWidgets.QPushButton(self.tab)
        self.generalReport_btn.setGeometry(QtCore.QRect(1060, 20, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.generalReport_btn.setFont(font)
        self.generalReport_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.generalReport_btn.setObjectName("generalReport_btn")
        self.serviceReport_btn = QtWidgets.QPushButton(self.tab)
        self.serviceReport_btn.setGeometry(QtCore.QRect(1060, 140, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.serviceReport_btn.setFont(font)
        self.serviceReport_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.serviceReport_btn.setObjectName("serviceReport_btn")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1196, 28))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(10)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.save_backup = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.save_backup.setFont(font)
        self.save_backup.setObjectName("save_backup")
        self.import_backup = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(10)
        self.import_backup.setFont(font)
        self.import_backup.setObjectName("import_backup")
        self.menu.addAction(self.save_backup)
        self.menu.addAction(self.import_backup)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.report_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Revita Clinic"))
        self.groupBox.setTitle(_translate("MainWindow", "جستجو پرونده بیمار"))
        self.label_2.setText(_translate("MainWindow", "کد ملی:"))
        self.patientsLastNameSearch_btn.setText(_translate("MainWindow", "جستجو"))
        self.patientsIdentityCodeSearch_btn.setText(_translate("MainWindow", "جستجو"))
        self.label_6.setText(_translate("MainWindow", "نام خانوادگی:"))
        self.refreshPatientsList_btn.setText(_translate("MainWindow", "تازه‌سازی لیست بیماران"))
        self.label_3.setText(_translate("MainWindow", "کلینیک زیبایی رویتا "))
        self.patients_lst.setSortingEnabled(False)
        self.addPatient_btn.setText(_translate("MainWindow", "اضافه کردن بیمار"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("MainWindow", "صفحه اصلی"))
        self.label_9.setText(_translate("MainWindow", "نوبت‌ها"))
        self.groupBox_7.setTitle(_translate("MainWindow", "یادآوری‌ها"))
        self.appointmentSearchByDay_btn.setText(_translate("MainWindow", "جستجو"))
        self.appointmentSearchDaySelect_cmbox.setCurrentText(_translate("MainWindow", "امروز"))
        self.appointmentSearchDaySelect_cmbox.setItemText(0, _translate("MainWindow", "امروز"))
        self.appointmentSearchDaySelect_cmbox.setItemText(1, _translate("MainWindow", "فردا"))
        self.appointmentSearchDaySelect_cmbox.setItemText(2, _translate("MainWindow", "دو روز بعد"))
        self.appointmentSearchDaySelect_cmbox.setItemText(3, _translate("MainWindow", "سه روز بعد"))
        self.appointmentSearchDaySelect_cmbox.setItemText(4, _translate("MainWindow", "چهار روز بعد"))
        self.groupBox_8.setTitle(_translate("MainWindow", "تاریخ"))
        self.AppointmentSearchByDate_btn.setText(_translate("MainWindow", "جستجو"))
        self.groupBox_11.setTitle(_translate("MainWindow", "پیامک یادآوری"))
        self.sendToAllSMSByDays_cmbox.setCurrentText(_translate("MainWindow", "امروز"))
        self.sendToAllSMSByDays_cmbox.setItemText(0, _translate("MainWindow", "امروز"))
        self.sendToAllSMSByDays_cmbox.setItemText(1, _translate("MainWindow", "فردا"))
        self.sendToAllSMSByDays_cmbox.setItemText(2, _translate("MainWindow", "دو روز بعد"))
        self.sendToAllSMSByDays_cmbox.setItemText(3, _translate("MainWindow", "سه روز بعد"))
        self.sendToAllSMSByDays_cmbox.setItemText(4, _translate("MainWindow", "چهار روز بعد"))
        self.sendToAllSMSByDays_btn.setText(_translate("MainWindow", "ارسال پیامک "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notifications_tab), _translate("MainWindow", "یادآوری‌ نوبت‌ها"))
        self.groupBox_4.setTitle(_translate("MainWindow", "جستجو سرویس‌ها"))
        self.searchServices_btn.setText(_translate("MainWindow", "جستجو"))
        self.label_11.setText(_translate("MainWindow", "نام سرویس:"))
        self.addServices_btn.setText(_translate("MainWindow", "اضافه کردن سرویس"))
        self.label_8.setText(_translate("MainWindow", "مدیریت سرویس‌ها"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.services_tab), _translate("MainWindow", "سرویس‌ها"))
        self.addDoctor_btn.setText(_translate("MainWindow", "اضافه کردن پزشک"))
        self.groupBox_5.setTitle(_translate("MainWindow", "جستجو پزشک"))
        self.searchDoctor_btn.setText(_translate("MainWindow", "جستجو"))
        self.label_12.setText(_translate("MainWindow", "نام پزشک:"))
        self.label_4.setText(_translate("MainWindow", "مدیریت پزشک‌ها"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.medicalRecords_tab), _translate("MainWindow", "پزشک‌ها"))
        self.addExpense_btn.setText(_translate("MainWindow", "اضافه کردن هزینه"))
        self.label_10.setText(_translate("MainWindow", "مدیریت هزینه"))
        self.groupBox_10.setTitle(_translate("MainWindow", "جستجو بر اساس نام"))
        self.label_17.setText(_translate("MainWindow", "نام هزینه:"))
        self.searchExpenseByName_btn.setText(_translate("MainWindow", "جستجو"))
        self.groupBox_9.setTitle(_translate("MainWindow", "جستجو بر اساس تاریخ"))
        self.searchExpenseByDate_btn.setText(_translate("MainWindow", "جستجو"))
        self.label_14.setText(_translate("MainWindow", "از تاریخ:"))
        self.label_15.setText(_translate("MainWindow", "تا تاریخ:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "هزینه‌ها"))
        self.label_35.setText(_translate("MainWindow", "پرفروش‌ترین سرویس‌ها"))
        self.label_37.setText(_translate("MainWindow", "بیشترین‌ هزینه‌ها"))
        self.label_38.setText(_translate("MainWindow", "کل درآمد"))
        self.generalTime_cmbox.setCurrentText(_translate("MainWindow", "ماه جاری"))
        self.generalTime_cmbox.setItemText(0, _translate("MainWindow", "ماه جاری"))
        self.generalTime_cmbox.setItemText(1, _translate("MainWindow", "سال جاری"))
        self.generalTime_cmbox.setItemText(2, _translate("MainWindow", "سال گذشته"))
        self.generalIncome_lbl.setText(_translate("MainWindow", "۲۵.۰۰۰.۰۰۰ تومان"))
        self.label_39.setText(_translate("MainWindow", "کل هزینه‌"))
        self.generalExpense_lbl.setText(_translate("MainWindow", "۲۵.۰۰۰.۰۰۰ تومان"))
        self.profitType_lbl.setText(_translate("MainWindow", "سود / ضرر"))
        self.generalProfit_lbl.setText(_translate("MainWindow", "۲۵.۰۰۰.۰۰۰ تومان"))
        self.refreshGeneralReport_btn.setText(_translate("MainWindow", "تازه‌سازی گزارش کلی"))
        self.label_13.setText(_translate("MainWindow", "گزارش کلی"))
        self.n0ServiceHighSold_lbl.setText(_translate("MainWindow", "بوتاکس صورت"))
        self.n1ServiceHighSold_lbl.setText(_translate("MainWindow", "فیلر لب"))
        self.n2ServiceHighSold_lbl.setText(_translate("MainWindow", "لیزر فول بادی"))
        self.n3ServiceHighSold_lbl.setText(_translate("MainWindow", "زیگیل"))
        self.n0HighestExpense_lbl.setText(_translate("MainWindow", "خرید ویال های بوتاکس"))
        self.n1HighestExpense_lbl.setText(_translate("MainWindow", "حقوق"))
        self.n2HighestExpense_lbl.setText(_translate("MainWindow", "خرید شیرینی"))
        self.n3HighestExpense_lbl.setText(_translate("MainWindow", "بوتاکس صورت"))
        self.refreshServiceReport_btn.setText(_translate("MainWindow", "تازه‌سازی گزارش سرویس"))
        self.serviceReportTime_cmbox.setCurrentText(_translate("MainWindow", "ماه جاری"))
        self.serviceReportTime_cmbox.setItemText(0, _translate("MainWindow", "ماه جاری"))
        self.serviceReportTime_cmbox.setItemText(1, _translate("MainWindow", "سال جاری"))
        self.serviceReportTime_cmbox.setItemText(2, _translate("MainWindow", "سال گذشته"))
        self.reportService_cmbox.setCurrentText(_translate("MainWindow", "بوتاکس"))
        self.reportService_cmbox.setItemText(0, _translate("MainWindow", "بوتاکس"))
        self.n3DayServiceHighSell_lbl.setText(_translate("MainWindow", "-"))
        self.label_50.setText(_translate("MainWindow", "پر فروش‌ترین روز‌های سرویس"))
        self.n0DayServiceHighSell_lbl.setText(_translate("MainWindow", "-"))
        self.n2DayServiceHighSell_lbl.setText(_translate("MainWindow", "-"))
        self.n1DayServiceHighSell_lbl.setText(_translate("MainWindow", "-"))
        self.label_51.setText(_translate("MainWindow", "کل درآمد سرویس"))
        self.serviceIncome_lbl.setText(_translate("MainWindow", "۲۵.۰۰۰.۰۰۰ تومان"))
        self.label_16.setText(_translate("MainWindow", "گزارش سرویس"))
        self.label_61.setText(_translate("MainWindow", "تعداد ارائه شدن سرویس"))
        self.serviceCount_lbl.setText(_translate("MainWindow", "۴۷"))
        self.generalReport_btn.setText(_translate("MainWindow", "گزارش کلی"))
        self.serviceReport_btn.setText(_translate("MainWindow", "گزارش سرویس"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "گزارش‌ها"))
        self.menu.setTitle(_translate("MainWindow", "پشتیبان"))
        self.save_backup.setText(_translate("MainWindow", "ذخیره فایل پشتیبان داده "))
        self.import_backup.setText(_translate("MainWindow", "وارد کردن فایل پشتیبان"))