# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1196, 723)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1196, 723))
        MainWindow.setMaximumSize(QtCore.QSize(1196, 723))
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1191, 711))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn SemiBold")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.groupBox = QtWidgets.QGroupBox(self.main_tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 89, 1151, 71))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.patientsIdentityCodeSearch_txtbox = QtWidgets.QLineEdit(self.groupBox)
        self.patientsIdentityCodeSearch_txtbox.setGeometry(QtCore.QRect(210, 30, 201, 31))
        self.patientsIdentityCodeSearch_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.patientsIdentityCodeSearch_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.patientsIdentityCodeSearch_txtbox.setObjectName("patientsIdentityCodeSearch_txtbox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(410, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.patientsLastNameSearch_btn = QtWidgets.QPushButton(self.groupBox)
        self.patientsLastNameSearch_btn.setGeometry(QtCore.QRect(490, 30, 71, 31))
        self.patientsLastNameSearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.patientsLastNameSearch_btn.setObjectName("patientsLastNameSearch_btn")
        self.patientsLastNameSearch_txtbox = QtWidgets.QLineEdit(self.groupBox)
        self.patientsLastNameSearch_txtbox.setGeometry(QtCore.QRect(570, 30, 221, 31))
        self.patientsLastNameSearch_txtbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.patientsLastNameSearch_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.patientsLastNameSearch_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.patientsLastNameSearch_txtbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.patientsLastNameSearch_txtbox.setObjectName("patientsLastNameSearch_txtbox")
        self.patientsIdentityCodeSearch_btn = QtWidgets.QPushButton(self.groupBox)
        self.patientsIdentityCodeSearch_btn.setGeometry(QtCore.QRect(130, 30, 71, 31))
        self.patientsIdentityCodeSearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.patientsIdentityCodeSearch_btn.setObjectName("patientsIdentityCodeSearch_btn")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(770, 30, 101, 31))
        self.label_6.setObjectName("label_6")
        self.refreshPatientsList_btn = QtWidgets.QPushButton(self.groupBox)
        self.refreshPatientsList_btn.setGeometry(QtCore.QRect(950, 30, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.refreshPatientsList_btn.setFont(font)
        self.refreshPatientsList_btn.setStyleSheet("QPushButton {\n"
"    background-color: #17a2b8; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.refreshPatientsList_btn.setObjectName("refreshPatientsList_btn")
        self.label_3 = QtWidgets.QLabel(self.main_tab)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 731, 81))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.patients_lst = QtWidgets.QListWidget(self.main_tab)
        self.patients_lst.setGeometry(QtCore.QRect(20, 170, 1151, 471))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.patients_lst.setFont(font)
        self.patients_lst.setMouseTracking(False)
        self.patients_lst.setAutoFillBackground(False)
        self.patients_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.patients_lst.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patients_lst.setFrameShadow(QtWidgets.QFrame.Raised)
        self.patients_lst.setLineWidth(1)
        self.patients_lst.setMidLineWidth(0)
        self.patients_lst.setDragDropOverwriteMode(False)
        self.patients_lst.setAlternatingRowColors(False)
        self.patients_lst.setViewMode(QtWidgets.QListView.ListMode)
        self.patients_lst.setUniformItemSizes(False)
        self.patients_lst.setWordWrap(False)
        self.patients_lst.setObjectName("patients_lst")
        self.addPatient_btn = QtWidgets.QPushButton(self.main_tab)
        self.addPatient_btn.setGeometry(QtCore.QRect(970, 30, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addPatient_btn.setFont(font)
        self.addPatient_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addPatient_btn.setObjectName("addPatient_btn")
        self.tabWidget.addTab(self.main_tab, "")
        self.appointments_tab = QtWidgets.QWidget()
        self.appointments_tab.setObjectName("appointments_tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.appointments_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 120, 1161, 531))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.appointments_lst = QtWidgets.QListWidget(self.groupBox_3)
        self.appointments_lst.setGeometry(QtCore.QRect(10, 30, 671, 491))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.appointments_lst.setFont(font)
        self.appointments_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.appointments_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.appointments_lst.setObjectName("appointments_lst")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(700, 80, 441, 161))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.day_spnbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.day_spnbox.setGeometry(QtCore.QRect(310, 40, 51, 31))
        self.day_spnbox.setMinimum(1)
        self.day_spnbox.setMaximum(31)
        self.day_spnbox.setObjectName("day_spnbox")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(350, 40, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_38.setObjectName("label_38")
        self.month_spnbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.month_spnbox.setGeometry(QtCore.QRect(200, 40, 51, 31))
        self.month_spnbox.setMinimum(1)
        self.month_spnbox.setMaximum(12)
        self.month_spnbox.setObjectName("month_spnbox")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(239, 40, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_39.setObjectName("label_39")
        self.year_spnbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.year_spnbox.setGeometry(QtCore.QRect(50, 40, 91, 31))
        self.year_spnbox.setMinimum(1400)
        self.year_spnbox.setMaximum(1500)
        self.year_spnbox.setObjectName("year_spnbox")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(130, 40, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_40.setObjectName("label_40")
        self.searchByDate_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.searchByDate_btn.setGeometry(QtCore.QRect(80, 110, 291, 41))
        self.searchByDate_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.searchByDate_btn.setObjectName("searchByDate_btn")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(700, 280, 441, 181))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.appointmentSearchPatientIdentityCode_txtbox = QtWidgets.QLineEdit(self.groupBox_6)
        self.appointmentSearchPatientIdentityCode_txtbox.setGeometry(QtCore.QRect(90, 70, 261, 31))
        self.appointmentSearchPatientIdentityCode_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.appointmentSearchPatientIdentityCode_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.appointmentSearchPatientIdentityCode_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.appointmentSearchPatientIdentityCode_txtbox.setObjectName("appointmentSearchPatientIdentityCode_txtbox")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(330, 80, 71, 20))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(350, 40, 61, 20))
        self.label_5.setObjectName("label_5")
        self.appointmentSearchPatientName_txtbox = QtWidgets.QLineEdit(self.groupBox_6)
        self.appointmentSearchPatientName_txtbox.setGeometry(QtCore.QRect(90, 30, 261, 31))
        self.appointmentSearchPatientName_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.appointmentSearchPatientName_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.appointmentSearchPatientName_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.appointmentSearchPatientName_txtbox.setObjectName("appointmentSearchPatientName_txtbox")
        self.searchByPatientsInfo_btn = QtWidgets.QPushButton(self.groupBox_6)
        self.searchByPatientsInfo_btn.setGeometry(QtCore.QRect(70, 130, 311, 41))
        self.searchByPatientsInfo_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.searchByPatientsInfo_btn.setObjectName("searchByPatientsInfo_btn")
        self.addAppointment_btn = QtWidgets.QPushButton(self.appointments_tab)
        self.addAppointment_btn.setGeometry(QtCore.QRect(980, 50, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addAppointment_btn.setFont(font)
        self.addAppointment_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addAppointment_btn.setObjectName("addAppointment_btn")
        self.label_13 = QtWidgets.QLabel(self.appointments_tab)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 941, 101))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.appointments_tab, "")
        self.notifications_tab = QtWidgets.QWidget()
        self.notifications_tab.setObjectName("notifications_tab")
        self.remainderAppointments_lst = QtWidgets.QListWidget(self.notifications_tab)
        self.remainderAppointments_lst.setGeometry(QtCore.QRect(140, 90, 571, 551))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.remainderAppointments_lst.setFont(font)
        self.remainderAppointments_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.remainderAppointments_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.remainderAppointments_lst.setObjectName("remainderAppointments_lst")
        self.oneDaySearch_btn = QtWidgets.QPushButton(self.notifications_tab)
        self.oneDaySearch_btn.setGeometry(QtCore.QRect(770, 160, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.oneDaySearch_btn.setFont(font)
        self.oneDaySearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.oneDaySearch_btn.setObjectName("oneDaySearch_btn")
        self.twoDaySearch_btn = QtWidgets.QPushButton(self.notifications_tab)
        self.twoDaySearch_btn.setGeometry(QtCore.QRect(770, 210, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.twoDaySearch_btn.setFont(font)
        self.twoDaySearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.twoDaySearch_btn.setObjectName("twoDaySearch_btn")
        self.fiveDaySearch_btn = QtWidgets.QPushButton(self.notifications_tab)
        self.fiveDaySearch_btn.setGeometry(QtCore.QRect(770, 360, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.fiveDaySearch_btn.setFont(font)
        self.fiveDaySearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.fiveDaySearch_btn.setObjectName("fiveDaySearch_btn")
        self.threeDaySearch_btn = QtWidgets.QPushButton(self.notifications_tab)
        self.threeDaySearch_btn.setGeometry(QtCore.QRect(770, 260, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.threeDaySearch_btn.setFont(font)
        self.threeDaySearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.threeDaySearch_btn.setObjectName("threeDaySearch_btn")
        self.fourDaySearch_btn = QtWidgets.QPushButton(self.notifications_tab)
        self.fourDaySearch_btn.setGeometry(QtCore.QRect(770, 310, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.fourDaySearch_btn.setFont(font)
        self.fourDaySearch_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.fourDaySearch_btn.setObjectName("fourDaySearch_btn")
        self.label_9 = QtWidgets.QLabel(self.notifications_tab)
        self.label_9.setGeometry(QtCore.QRect(140, 0, 571, 81))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.notifications_tab, "")
        self.services_tab = QtWidgets.QWidget()
        self.services_tab.setObjectName("services_tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.services_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 110, 1161, 531))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.searchServices_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.searchServices_btn.setGeometry(QtCore.QRect(680, 40, 111, 31))
        self.searchServices_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    box-shadow: 0 4px rgba(0, 0, 0, 0.2); /* Shadow */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"    box-shadow: 0 2px rgba(0, 0, 0, 0.2); /* Reduce shadow on press */\n"
"    transform: translateY(2px); /* Move button down on press */\n"
"}\n"
"")
        self.searchServices_btn.setObjectName("searchServices_btn")
        self.services_lst = QtWidgets.QListWidget(self.groupBox_4)
        self.services_lst.setGeometry(QtCore.QRect(10, 90, 1141, 431))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.services_lst.setFont(font)
        self.services_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.services_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.services_lst.setObjectName("services_lst")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(1060, 50, 81, 20))
        self.label_11.setObjectName("label_11")
        self.serviceName_txtbox = QtWidgets.QLineEdit(self.groupBox_4)
        self.serviceName_txtbox.setGeometry(QtCore.QRect(800, 40, 261, 31))
        self.serviceName_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.serviceName_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.serviceName_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.serviceName_txtbox.setText("")
        self.serviceName_txtbox.setObjectName("serviceName_txtbox")
        self.addServices_btn = QtWidgets.QPushButton(self.services_tab)
        self.addServices_btn.setGeometry(QtCore.QRect(980, 50, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addServices_btn.setFont(font)
        self.addServices_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addServices_btn.setObjectName("addServices_btn")
        self.label_8 = QtWidgets.QLabel(self.services_tab)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 941, 101))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.services_tab, "")
        self.medicalRecords_tab = QtWidgets.QWidget()
        self.medicalRecords_tab.setObjectName("medicalRecords_tab")
        self.addDoctor_btn = QtWidgets.QPushButton(self.medicalRecords_tab)
        self.addDoctor_btn.setGeometry(QtCore.QRect(980, 50, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addDoctor_btn.setFont(font)
        self.addDoctor_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.addDoctor_btn.setObjectName("addDoctor_btn")
        self.groupBox_5 = QtWidgets.QGroupBox(self.medicalRecords_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 110, 1161, 531))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.searchDoctor_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.searchDoctor_btn.setGeometry(QtCore.QRect(680, 40, 111, 31))
        self.searchDoctor_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 16px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.searchDoctor_btn.setObjectName("searchDoctor_btn")
        self.doctors_lst = QtWidgets.QListWidget(self.groupBox_5)
        self.doctors_lst.setGeometry(QtCore.QRect(10, 90, 1141, 431))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        self.doctors_lst.setFont(font)
        self.doctors_lst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.doctors_lst.setStyleSheet("/* Basic ListWidget styling */\n"
"QListWidget {\n"
"    background-color: #f8f9fa; /* Light grey background */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the list */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 17px; /* Font size */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Item styling */\n"
"QListWidget::item {\n"
"    padding: 10px 15px; /* Padding for each item */\n"
"    margin: 5px 0; /* Margin between items */\n"
"    background-color: #ffffff; /* White background for items */\n"
"    border-radius: 5px; /* Rounded corners for items */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: 0; /* Remove focus indicator */\n"
"}\n"
"\n"
"/* Hover effect for items */\n"
"QListWidget::item:hover {\n"
"    background-color: #e9ecef; /* Light grey background on hover */\n"
"}\n"
"\n"
"/* Selected item styling */\n"
"QListWidget::item:selected {\n"
"    background-color: #0050a5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll bar styling */\n"
"QScrollBar:vertical {\n"
"    background: #f8f9fa; /* Light grey background for the scroll bar */\n"
"    width: 12px; /* Width of the vertical scroll bar */\n"
"    margin: 22px 0 22px 0; /* Margin to fit the top and bottom arrows */\n"
"    border: 1px solid #dee2e6; /* Border color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ced4da; /* Medium grey handle */\n"
"    min-height: 20px; /* Minimum height of the handle */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ced4da; /* Medium grey for arrows */\n"
"    height: 20px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.doctors_lst.setObjectName("doctors_lst")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(1070, 50, 71, 20))
        self.label_12.setObjectName("label_12")
        self.doctorName_txtbox = QtWidgets.QLineEdit(self.groupBox_5)
        self.doctorName_txtbox.setGeometry(QtCore.QRect(800, 40, 261, 31))
        self.doctorName_txtbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.doctorName_txtbox.setStyleSheet("/* Basic LineEdit styling */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White background */\n"
"    border: 1px solid #dee2e6; /* Light grey border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"    font-size: 16px; /* Font size */\n"
"    color: #343a40; /* Dark grey text color */\n"
"    outline: none; /* Remove default outline */\n"
"    transition: border-color 0.3s, box-shadow 0.3s; /* Smooth transition */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLineEdit:hover {\n"
"    border: 1px solid #007bff; /* Blue border on hover */\n"
"}\n"
"\n"
"/* Focus effect */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007bff; /* Blue border on focus */\n"
"    box-shadow: 0 0 5px rgba(0, 123, 255, 0.5); /* Blue shadow on focus */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QLineEdit:disabled {\n"
"    background-color: #e9ecef; /* Light grey background when disabled */\n"
"    color: #6c757d; /* Grey text color when disabled */\n"
"}\n"
"\n"
"")
        self.doctorName_txtbox.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.doctorName_txtbox.setText("")
        self.doctorName_txtbox.setObjectName("doctorName_txtbox")
        self.label_4 = QtWidgets.QLabel(self.medicalRecords_tab)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 931, 101))
        font = QtGui.QFont()
        font.setFamily("A Rezvan-fat,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("/* Basic styling for the company name label */\n"
"QLabel {\n"
"    color: #007bff; /* Bootstrap primary blue text color */\n"
"    font-family: \'A Rezvan-fat\', sans-serif; /* Font family */\n"
"    font-size: 30px; /* Larger font size for prominence */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px; /* Padding around the text */\n"
"    border: 2px solid #007bff; /* Optional: Border with the same blue color */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    background-color: #f8f9fa; /* Light grey background to make it stand out */\n"
"    text-align: center; /* Center-align the text */\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QLabe:hover {\n"
"    color: #0056b3; /* Darker blue on hover */\n"
"    border-color: #0056b3; /* Match border color on hover */\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.medicalRecords_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Revita Clinic"))
        self.groupBox.setTitle(_translate("MainWindow", "جستجو پرونده بیمار"))
        self.label_2.setText(_translate("MainWindow", "کد ملی:"))
        self.patientsLastNameSearch_btn.setText(_translate("MainWindow", "جستجو"))
        self.patientsIdentityCodeSearch_btn.setText(_translate("MainWindow", "جستجو"))
        self.label_6.setText(_translate("MainWindow", "نام خانوادگی:"))
        self.refreshPatientsList_btn.setText(_translate("MainWindow", "تازه‌سازی لیست بیماران"))
        self.label_3.setText(_translate("MainWindow", "کلینیک زیبایی رویتا "))
        self.patients_lst.setSortingEnabled(False)
        self.addPatient_btn.setText(_translate("MainWindow", "اضافه کردن بیمار"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("MainWindow", "صفحه اصلی"))
        self.groupBox_3.setTitle(_translate("MainWindow", "جستجو نوبت‌ها"))
        self.groupBox_2.setTitle(_translate("MainWindow", "تاریخ"))
        self.label_38.setText(_translate("MainWindow", "روز:"))
        self.label_39.setText(_translate("MainWindow", "ماه:"))
        self.label_40.setText(_translate("MainWindow", "سال:"))
        self.searchByDate_btn.setText(_translate("MainWindow", "جستجو بر اساس تاریخ"))
        self.groupBox_6.setTitle(_translate("MainWindow", "اطلاعات بیمار"))
        self.label_7.setText(_translate("MainWindow", "کد ملی:"))
        self.label_5.setText(_translate("MainWindow", "نام بیمار: "))
        self.searchByPatientsInfo_btn.setText(_translate("MainWindow", "جستجو بر اساس اطلاعات بیمار"))
        self.addAppointment_btn.setText(_translate("MainWindow", "اضافه کردن نوبت"))
        self.label_13.setText(_translate("MainWindow", "مدیریت نوبت‌ها"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appointments_tab), _translate("MainWindow", "نوبت‌ها"))
        self.oneDaySearch_btn.setText(_translate("MainWindow", "یک روز بعد"))
        self.twoDaySearch_btn.setText(_translate("MainWindow", "دو روز بعد"))
        self.fiveDaySearch_btn.setText(_translate("MainWindow", "پنچ روز بعد"))
        self.threeDaySearch_btn.setText(_translate("MainWindow", "سه روز بعد"))
        self.fourDaySearch_btn.setText(_translate("MainWindow", "چهار روز بعد"))
        self.label_9.setText(_translate("MainWindow", "یادآوری نوبت‌ها"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notifications_tab), _translate("MainWindow", "یادآوری‌ها"))
        self.groupBox_4.setTitle(_translate("MainWindow", "جستجو سرویس‌ها"))
        self.searchServices_btn.setText(_translate("MainWindow", "جستجو"))
        self.label_11.setText(_translate("MainWindow", "نام سرویس:"))
        self.addServices_btn.setText(_translate("MainWindow", "اضافه کردن سرویس"))
        self.label_8.setText(_translate("MainWindow", "مدیریت سرویس‌ها"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.services_tab), _translate("MainWindow", "سرویس‌ها"))
        self.addDoctor_btn.setText(_translate("MainWindow", "اضافه کردن پزشک"))
        self.groupBox_5.setTitle(_translate("MainWindow", "جستجو پزشک"))
        self.searchDoctor_btn.setText(_translate("MainWindow", "جستجو"))
        self.label_12.setText(_translate("MainWindow", "نام پزشک:"))
        self.label_4.setText(_translate("MainWindow", "مدیریت پزشک‌ها"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.medicalRecords_tab), _translate("MainWindow", "پزشک‌ها"))

