# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medical_record_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_medicalRecordInfo_form(object):
    def setupUi(self, medicalRecordInfo_form):
        medicalRecordInfo_form.setObjectName("medicalRecordInfo_form")
        medicalRecordInfo_form.resize(641, 361)
        medicalRecordInfo_form.setMinimumSize(QtCore.QSize(641, 361))
        medicalRecordInfo_form.setMaximumSize(QtCore.QSize(641, 361))
        self.editMedicalRecord_btn = QtWidgets.QPushButton(medicalRecordInfo_form)
        self.editMedicalRecord_btn.setGeometry(QtCore.QRect(330, 310, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.editMedicalRecord_btn.setFont(font)
        self.editMedicalRecord_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.editMedicalRecord_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ffc107; /* Bootstrap warning yellow */\n"
"    color: #212529; /* Dark text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0a800; /* Darker yellow on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c69500; /* Even darker yellow on press */\n"
"}\n"
"")
        self.editMedicalRecord_btn.setObjectName("editMedicalRecord_btn")
        self.line_4 = QtWidgets.QFrame(medicalRecordInfo_form)
        self.line_4.setGeometry(QtCore.QRect(10, 200, 621, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.date_lbl = QtWidgets.QLabel(medicalRecordInfo_form)
        self.date_lbl.setGeometry(QtCore.QRect(6, 70, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.date_lbl.setFont(font)
        self.date_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.date_lbl.setObjectName("date_lbl")
        self.line_7 = QtWidgets.QFrame(medicalRecordInfo_form)
        self.line_7.setGeometry(QtCore.QRect(510, 20, 20, 281))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.patientFullName_lbl = QtWidgets.QLabel(medicalRecordInfo_form)
        self.patientFullName_lbl.setGeometry(QtCore.QRect(0, 20, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.patientFullName_lbl.setFont(font)
        self.patientFullName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.patientFullName_lbl.setObjectName("patientFullName_lbl")
        self.serviceName_lbl = QtWidgets.QLabel(medicalRecordInfo_form)
        self.serviceName_lbl.setGeometry(QtCore.QRect(10, 170, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.serviceName_lbl.setFont(font)
        self.serviceName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.serviceName_lbl.setObjectName("serviceName_lbl")
        self.line = QtWidgets.QFrame(medicalRecordInfo_form)
        self.line.setGeometry(QtCore.QRect(10, 50, 621, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(medicalRecordInfo_form)
        self.line_2.setGeometry(QtCore.QRect(10, 100, 621, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.doctorName_lbl = QtWidgets.QLabel(medicalRecordInfo_form)
        self.doctorName_lbl.setGeometry(QtCore.QRect(10, 120, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(13)
        self.doctorName_lbl.setFont(font)
        self.doctorName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.doctorName_lbl.setObjectName("doctorName_lbl")
        self.label_35 = QtWidgets.QLabel(medicalRecordInfo_form)
        self.label_35.setGeometry(QtCore.QRect(530, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_46 = QtWidgets.QLabel(medicalRecordInfo_form)
        self.label_46.setGeometry(QtCore.QRect(530, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_45 = QtWidgets.QLabel(medicalRecordInfo_form)
        self.label_45.setGeometry(QtCore.QRect(530, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.deleteMedicalRecord_btn = QtWidgets.QPushButton(medicalRecordInfo_form)
        self.deleteMedicalRecord_btn.setGeometry(QtCore.QRect(540, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.deleteMedicalRecord_btn.setFont(font)
        self.deleteMedicalRecord_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.deleteMedicalRecord_btn.setStyleSheet("QPushButton{\n"
"    background-color: #dc3545; /* Bootstrap danger red */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c82333; /* Darker red on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #bd2130; /* Even darker red on press */\n"
"}\n"
"")
        self.deleteMedicalRecord_btn.setObjectName("deleteMedicalRecord_btn")
        self.label_40 = QtWidgets.QLabel(medicalRecordInfo_form)
        self.label_40.setGeometry(QtCore.QRect(530, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_39 = QtWidgets.QLabel(medicalRecordInfo_form)
        self.label_39.setGeometry(QtCore.QRect(530, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.description_lbl = QtWidgets.QLabel(medicalRecordInfo_form)
        self.description_lbl.setGeometry(QtCore.QRect(10, 270, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(12)
        self.description_lbl.setFont(font)
        self.description_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.description_lbl.setObjectName("description_lbl")
        self.line_3 = QtWidgets.QFrame(medicalRecordInfo_form)
        self.line_3.setGeometry(QtCore.QRect(10, 150, 621, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.showPictures_btn = QtWidgets.QPushButton(medicalRecordInfo_form)
        self.showPictures_btn.setGeometry(QtCore.QRect(10, 310, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.showPictures_btn.setFont(font)
        self.showPictures_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0050a5; /* Bootstrap primary blue */\n"
"    color: white; /* White text */\n"
"    border: none;\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 15px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family: \'Vazirmatn\', sans-serif; /* Font family */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004085; /* Even darker blue on press */\n"
"}\n"
"")
        self.showPictures_btn.setObjectName("showPictures_btn")
        self.label_47 = QtWidgets.QLabel(medicalRecordInfo_form)
        self.label_47.setGeometry(QtCore.QRect(530, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn ExtraBold")
        font.setPointSize(13)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.line_5 = QtWidgets.QFrame(medicalRecordInfo_form)
        self.line_5.setGeometry(QtCore.QRect(10, 250, 621, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.price_lbl = QtWidgets.QLabel(medicalRecordInfo_form)
        self.price_lbl.setGeometry(QtCore.QRect(10, 220, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Vazirmatn")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.price_lbl.setFont(font)
        self.price_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.price_lbl.setObjectName("price_lbl")

        self.retranslateUi(medicalRecordInfo_form)
        QtCore.QMetaObject.connectSlotsByName(medicalRecordInfo_form)

    def retranslateUi(self, medicalRecordInfo_form):
        _translate = QtCore.QCoreApplication.translate
        medicalRecordInfo_form.setWindowTitle(_translate("medicalRecordInfo_form", "اطلاعات خدمات بیمار"))
        self.editMedicalRecord_btn.setText(_translate("medicalRecordInfo_form", "ویرایش "))
        self.date_lbl.setText(_translate("medicalRecordInfo_form", "سه‌شنبه ۱۴۰۳/۰۱/۰۵ ۱۵:۳۰"))
        self.patientFullName_lbl.setText(_translate("medicalRecordInfo_form", "امیررضا خلیلی"))
        self.serviceName_lbl.setText(_translate("medicalRecordInfo_form", "بوتاکس صورت"))
        self.doctorName_lbl.setText(_translate("medicalRecordInfo_form", "دکتر محمدرضا خلیلی"))
        self.label_35.setText(_translate("medicalRecordInfo_form", "نام بیمار:"))
        self.label_46.setText(_translate("medicalRecordInfo_form", "توضیحات:"))
        self.label_45.setText(_translate("medicalRecordInfo_form", "تاریخ:"))
        self.deleteMedicalRecord_btn.setText(_translate("medicalRecordInfo_form", "حذف "))
        self.label_40.setText(_translate("medicalRecordInfo_form", "سرویس:"))
        self.label_39.setText(_translate("medicalRecordInfo_form", "دکتر:"))
        self.description_lbl.setText(_translate("medicalRecordInfo_form", "جلسه سوم"))
        self.showPictures_btn.setText(_translate("medicalRecordInfo_form", "نمایش تصاویر"))
        self.label_47.setText(_translate("medicalRecordInfo_form", "قیمت:"))
        self.price_lbl.setText(_translate("medicalRecordInfo_form", "۲۵۰,۰۰۰ تومان"))

